#include "php.h"
#include "zend_ast.h"
#include "zend_attributes.h"
#include "zend_language_scanner.h"
#include "zend_inheritance.h"
#include "zend_hash.h"
#include "zend_modules.h"
#include "zend_arena.h"
#include "zend_exceptions.h"
#include "Optimizer/zend_optimizer.h"
#include "supplement.h"
#include <stdio.h>

int main(void) {
    FILE *constants = fopen("constants.php", "w");
    FILE *layouts   = fopen("layouts.json", "w");
    if (!constants || !layouts) { return 1; }
    fputs("<?php\n\n/* Generated by tools/generator - DO NOT EDIT */\n\nreturn [\n", constants);
#ifdef ZEND_ACC_PUBLIC
    fprintf(constants, "    'ZEND_ACC_PUBLIC' => %lld,\n", (long long)(ZEND_ACC_PUBLIC));
#endif
#ifdef ZEND_ACC_PROTECTED
    fprintf(constants, "    'ZEND_ACC_PROTECTED' => %lld,\n", (long long)(ZEND_ACC_PROTECTED));
#endif
#ifdef ZEND_ACC_PRIVATE
    fprintf(constants, "    'ZEND_ACC_PRIVATE' => %lld,\n", (long long)(ZEND_ACC_PRIVATE));
#endif
#ifdef ZEND_ACC_CHANGED
    fprintf(constants, "    'ZEND_ACC_CHANGED' => %lld,\n", (long long)(ZEND_ACC_CHANGED));
#endif
#ifdef ZEND_ACC_STATIC
    fprintf(constants, "    'ZEND_ACC_STATIC' => %lld,\n", (long long)(ZEND_ACC_STATIC));
#endif
#ifdef ZEND_ACC_ABSTRACT
    fprintf(constants, "    'ZEND_ACC_ABSTRACT' => %lld,\n", (long long)(ZEND_ACC_ABSTRACT));
#endif
#ifdef ZEND_ACC_FINAL
    fprintf(constants, "    'ZEND_ACC_FINAL' => %lld,\n", (long long)(ZEND_ACC_FINAL));
#endif
#ifdef ZEND_ACC_DEPRECATED
    fprintf(constants, "    'ZEND_ACC_DEPRECATED' => %lld,\n", (long long)(ZEND_ACC_DEPRECATED));
#endif
#ifdef ZEND_ACC_INTERFACE
    fprintf(constants, "    'ZEND_ACC_INTERFACE' => %lld,\n", (long long)(ZEND_ACC_INTERFACE));
#endif
#ifdef ZEND_ACC_TRAIT
    fprintf(constants, "    'ZEND_ACC_TRAIT' => %lld,\n", (long long)(ZEND_ACC_TRAIT));
#endif
#ifdef ZEND_ACC_ANON_CLASS
    fprintf(constants, "    'ZEND_ACC_ANON_CLASS' => %lld,\n", (long long)(ZEND_ACC_ANON_CLASS));
#endif
#ifdef ZEND_ACC_ENUM
    fprintf(constants, "    'ZEND_ACC_ENUM' => %lld,\n", (long long)(ZEND_ACC_ENUM));
#endif
#ifdef ZEND_ACC_IMPLICIT_ABSTRACT_CLASS
    fprintf(constants, "    'ZEND_ACC_IMPLICIT_ABSTRACT_CLASS' => %lld,\n", (long long)(ZEND_ACC_IMPLICIT_ABSTRACT_CLASS));
#endif
#ifdef ZEND_ACC_LINKED
    fprintf(constants, "    'ZEND_ACC_LINKED' => %lld,\n", (long long)(ZEND_ACC_LINKED));
#endif
#ifdef ZEND_ACC_IMMUTABLE
    fprintf(constants, "    'ZEND_ACC_IMMUTABLE' => %lld,\n", (long long)(ZEND_ACC_IMMUTABLE));
#endif
#ifdef ZEND_ACC_USE_GUARDS
    fprintf(constants, "    'ZEND_ACC_USE_GUARDS' => %lld,\n", (long long)(ZEND_ACC_USE_GUARDS));
#endif
#ifdef ZEND_ACC_CONSTANTS_UPDATED
    fprintf(constants, "    'ZEND_ACC_CONSTANTS_UPDATED' => %lld,\n", (long long)(ZEND_ACC_CONSTANTS_UPDATED));
#endif
#ifdef ZEND_ACC_NO_DYNAMIC_PROPERTIES
    fprintf(constants, "    'ZEND_ACC_NO_DYNAMIC_PROPERTIES' => %lld,\n", (long long)(ZEND_ACC_NO_DYNAMIC_PROPERTIES));
#endif
#ifdef ZEND_ACC_HAS_STATIC_IN_METHODS
    fprintf(constants, "    'ZEND_ACC_HAS_STATIC_IN_METHODS' => %lld,\n", (long long)(ZEND_ACC_HAS_STATIC_IN_METHODS));
#endif
#ifdef ZEND_HAS_STATIC_IN_METHODS
    fprintf(constants, "    'ZEND_HAS_STATIC_IN_METHODS' => %lld,\n", (long long)(ZEND_HAS_STATIC_IN_METHODS));
#endif
#ifdef ZEND_ACC_TOP_LEVEL
    fprintf(constants, "    'ZEND_ACC_TOP_LEVEL' => %lld,\n", (long long)(ZEND_ACC_TOP_LEVEL));
#endif
#ifdef ZEND_ACC_PRELOADED
    fprintf(constants, "    'ZEND_ACC_PRELOADED' => %lld,\n", (long long)(ZEND_ACC_PRELOADED));
#endif
#ifdef ZEND_ACC_NOT_SERIALIZABLE
    fprintf(constants, "    'ZEND_ACC_NOT_SERIALIZABLE' => %lld,\n", (long long)(ZEND_ACC_NOT_SERIALIZABLE));
#endif
#ifdef ZEND_ACC_READONLY_CLASS
    fprintf(constants, "    'ZEND_ACC_READONLY_CLASS' => %lld,\n", (long long)(ZEND_ACC_READONLY_CLASS));
#endif
#ifdef ZEND_ACC_ALLOW_DYNAMIC_PROPERTIES
    fprintf(constants, "    'ZEND_ACC_ALLOW_DYNAMIC_PROPERTIES' => %lld,\n", (long long)(ZEND_ACC_ALLOW_DYNAMIC_PROPERTIES));
#endif
#ifdef ZEND_ACC_UNRESOLVED_VARIANCE
    fprintf(constants, "    'ZEND_ACC_UNRESOLVED_VARIANCE' => %lld,\n", (long long)(ZEND_ACC_UNRESOLVED_VARIANCE));
#endif
#ifdef ZEND_ACC_NEARLY_LINKED
    fprintf(constants, "    'ZEND_ACC_NEARLY_LINKED' => %lld,\n", (long long)(ZEND_ACC_NEARLY_LINKED));
#endif
#ifdef ZEND_ACC_RESOLVED_PARENT
    fprintf(constants, "    'ZEND_ACC_RESOLVED_PARENT' => %lld,\n", (long long)(ZEND_ACC_RESOLVED_PARENT));
#endif
#ifdef ZEND_ACC_RESOLVED_INTERFACES
    fprintf(constants, "    'ZEND_ACC_RESOLVED_INTERFACES' => %lld,\n", (long long)(ZEND_ACC_RESOLVED_INTERFACES));
#endif
#ifdef ZEND_ACC_HAS_UNLINKED_USES
    fprintf(constants, "    'ZEND_ACC_HAS_UNLINKED_USES' => %lld,\n", (long long)(ZEND_ACC_HAS_UNLINKED_USES));
#endif
#ifdef ZEND_ACC_PROPERTY_TYPES_RESOLVED
    fprintf(constants, "    'ZEND_ACC_PROPERTY_TYPES_RESOLVED' => %lld,\n", (long long)(ZEND_ACC_PROPERTY_TYPES_RESOLVED));
#endif
#ifdef ZEND_ACC_REUSE_GET_ITERATOR
    fprintf(constants, "    'ZEND_ACC_REUSE_GET_ITERATOR' => %lld,\n", (long long)(ZEND_ACC_REUSE_GET_ITERATOR));
#endif
#ifdef ZEND_ACC_EXPLICIT_ABSTRACT_CLASS
    fprintf(constants, "    'ZEND_ACC_EXPLICIT_ABSTRACT_CLASS' => %lld,\n", (long long)(ZEND_ACC_EXPLICIT_ABSTRACT_CLASS));
#endif
#ifdef ZEND_ACC_READONLY
    fprintf(constants, "    'ZEND_ACC_READONLY' => %lld,\n", (long long)(ZEND_ACC_READONLY));
#endif
#ifdef ZEND_ACC_ABSTRACT_METHOD
    fprintf(constants, "    'ZEND_ACC_ABSTRACT_METHOD' => %lld,\n", (long long)(ZEND_ACC_ABSTRACT_METHOD));
#endif
#ifdef ZEND_ACC_VIRTUAL
    fprintf(constants, "    'ZEND_ACC_VIRTUAL' => %lld,\n", (long long)(ZEND_ACC_VIRTUAL));
#endif
#ifdef ZEND_ACC_FAKE_CLOSURE
    fprintf(constants, "    'ZEND_ACC_FAKE_CLOSURE' => %lld,\n", (long long)(ZEND_ACC_FAKE_CLOSURE));
#endif
#ifdef ZEND_ACC_UNINSTANTIABLE
    fprintf(constants, "    'ZEND_ACC_UNINSTANTIABLE' => %lld,\n", (long long)(ZEND_ACC_UNINSTANTIABLE));
#endif
#ifdef ZEND_ACC_CALL_VIA_TRAMPOLINE
    fprintf(constants, "    'ZEND_ACC_CALL_VIA_TRAMPOLINE' => %lld,\n", (long long)(ZEND_ACC_CALL_VIA_TRAMPOLINE));
#endif
#ifdef ZEND_ACC_NEVER_CACHE
    fprintf(constants, "    'ZEND_ACC_NEVER_CACHE' => %lld,\n", (long long)(ZEND_ACC_NEVER_CACHE));
#endif
#ifdef ZEND_ACC_TRAIT_CLONE
    fprintf(constants, "    'ZEND_ACC_TRAIT_CLONE' => %lld,\n", (long long)(ZEND_ACC_TRAIT_CLONE));
#endif
#ifdef ZEND_ACC_RETURN_REFERENCE
    fprintf(constants, "    'ZEND_ACC_RETURN_REFERENCE' => %lld,\n", (long long)(ZEND_ACC_RETURN_REFERENCE));
#endif
#ifdef ZEND_ACC_DONE_PASS_TWO
    fprintf(constants, "    'ZEND_ACC_DONE_PASS_TWO' => %lld,\n", (long long)(ZEND_ACC_DONE_PASS_TWO));
#endif
#ifdef ZEND_ACC_HEAP_RT_CACHE
    fprintf(constants, "    'ZEND_ACC_HEAP_RT_CACHE' => %lld,\n", (long long)(ZEND_ACC_HEAP_RT_CACHE));
#endif
#ifdef ZEND_ACC_STRICT_TYPES
    fprintf(constants, "    'ZEND_ACC_STRICT_TYPES' => %lld,\n", (long long)(ZEND_ACC_STRICT_TYPES));
#endif
#ifdef ZEND_ACC_CLOSURE
    fprintf(constants, "    'ZEND_ACC_CLOSURE' => %lld,\n", (long long)(ZEND_ACC_CLOSURE));
#endif
#ifdef ZEND_ACC_GENERATOR
    fprintf(constants, "    'ZEND_ACC_GENERATOR' => %lld,\n", (long long)(ZEND_ACC_GENERATOR));
#endif
#ifdef ZEND_ACC_HAS_FINALLY_BLOCK
    fprintf(constants, "    'ZEND_ACC_HAS_FINALLY_BLOCK' => %lld,\n", (long long)(ZEND_ACC_HAS_FINALLY_BLOCK));
#endif
#ifdef ZEND_ACC_EARLY_BINDING
    fprintf(constants, "    'ZEND_ACC_EARLY_BINDING' => %lld,\n", (long long)(ZEND_ACC_EARLY_BINDING));
#endif
#ifdef ZEND_ACC_USES_THIS
    fprintf(constants, "    'ZEND_ACC_USES_THIS' => %lld,\n", (long long)(ZEND_ACC_USES_THIS));
#endif
#ifdef ZEND_ACC_CTOR
    fprintf(constants, "    'ZEND_ACC_CTOR' => %lld,\n", (long long)(ZEND_ACC_CTOR));
#endif
#ifdef ZEND_ACC_HAS_TYPE_HINTS
    fprintf(constants, "    'ZEND_ACC_HAS_TYPE_HINTS' => %lld,\n", (long long)(ZEND_ACC_HAS_TYPE_HINTS));
#endif
#ifdef ZEND_ACC_HAS_RETURN_TYPE
    fprintf(constants, "    'ZEND_ACC_HAS_RETURN_TYPE' => %lld,\n", (long long)(ZEND_ACC_HAS_RETURN_TYPE));
#endif
#ifdef ZEND_ACC_VARIADIC
    fprintf(constants, "    'ZEND_ACC_VARIADIC' => %lld,\n", (long long)(ZEND_ACC_VARIADIC));
#endif
#ifdef ZEND_ACC_HAS_UNRESOLVED_INITIALIZERS
    fprintf(constants, "    'ZEND_ACC_HAS_UNRESOLVED_INITIALIZERS' => %lld,\n", (long long)(ZEND_ACC_HAS_UNRESOLVED_INITIALIZERS));
#endif
#ifdef ZEND_ACC_CACHED
    fprintf(constants, "    'ZEND_ACC_CACHED' => %lld,\n", (long long)(ZEND_ACC_CACHED));
#endif
#ifdef ZEND_ACC_FILE_CACHED
    fprintf(constants, "    'ZEND_ACC_FILE_CACHED' => %lld,\n", (long long)(ZEND_ACC_FILE_CACHED));
#endif
#ifdef ZEND_ACC_ARENA_ALLOCATED
    fprintf(constants, "    'ZEND_ACC_ARENA_ALLOCATED' => %lld,\n", (long long)(ZEND_ACC_ARENA_ALLOCATED));
#endif
#ifdef _ZEND_TYPE_EXTRA_FLAGS_SHIFT
    fprintf(constants, "    '_ZEND_TYPE_EXTRA_FLAGS_SHIFT' => %lld,\n", (long long)(_ZEND_TYPE_EXTRA_FLAGS_SHIFT));
#endif
#ifdef _ZEND_TYPE_MASK
    fprintf(constants, "    '_ZEND_TYPE_MASK' => %lld,\n", (long long)(_ZEND_TYPE_MASK));
#endif
#ifdef _ZEND_TYPE_NAME_BIT
    fprintf(constants, "    '_ZEND_TYPE_NAME_BIT' => %lld,\n", (long long)(_ZEND_TYPE_NAME_BIT));
#endif
#ifdef _ZEND_TYPE_LITERAL_NAME_BIT
    fprintf(constants, "    '_ZEND_TYPE_LITERAL_NAME_BIT' => %lld,\n", (long long)(_ZEND_TYPE_LITERAL_NAME_BIT));
#endif
#ifdef _ZEND_TYPE_LIST_BIT
    fprintf(constants, "    '_ZEND_TYPE_LIST_BIT' => %lld,\n", (long long)(_ZEND_TYPE_LIST_BIT));
#endif
#ifdef _ZEND_TYPE_KIND_MASK
    fprintf(constants, "    '_ZEND_TYPE_KIND_MASK' => %lld,\n", (long long)(_ZEND_TYPE_KIND_MASK));
#endif
#ifdef _ZEND_TYPE_ITERABLE_BIT
    fprintf(constants, "    '_ZEND_TYPE_ITERABLE_BIT' => %lld,\n", (long long)(_ZEND_TYPE_ITERABLE_BIT));
#endif
#ifdef _ZEND_TYPE_ARENA_BIT
    fprintf(constants, "    '_ZEND_TYPE_ARENA_BIT' => %lld,\n", (long long)(_ZEND_TYPE_ARENA_BIT));
#endif
#ifdef _ZEND_TYPE_INTERSECTION_BIT
    fprintf(constants, "    '_ZEND_TYPE_INTERSECTION_BIT' => %lld,\n", (long long)(_ZEND_TYPE_INTERSECTION_BIT));
#endif
#ifdef _ZEND_TYPE_UNION_BIT
    fprintf(constants, "    '_ZEND_TYPE_UNION_BIT' => %lld,\n", (long long)(_ZEND_TYPE_UNION_BIT));
#endif
#ifdef _ZEND_TYPE_NULLABLE_BIT
    fprintf(constants, "    '_ZEND_TYPE_NULLABLE_BIT' => %lld,\n", (long long)(_ZEND_TYPE_NULLABLE_BIT));
#endif
#ifdef _ZEND_TYPE_MAY_BE_MASK
    fprintf(constants, "    '_ZEND_TYPE_MAY_BE_MASK' => %lld,\n", (long long)(_ZEND_TYPE_MAY_BE_MASK));
#endif
#ifdef IS_UNDEF
    fprintf(constants, "    'IS_UNDEF' => %lld,\n", (long long)(IS_UNDEF));
#endif
#ifdef IS_NULL
    fprintf(constants, "    'IS_NULL' => %lld,\n", (long long)(IS_NULL));
#endif
#ifdef IS_FALSE
    fprintf(constants, "    'IS_FALSE' => %lld,\n", (long long)(IS_FALSE));
#endif
#ifdef IS_TRUE
    fprintf(constants, "    'IS_TRUE' => %lld,\n", (long long)(IS_TRUE));
#endif
#ifdef IS_LONG
    fprintf(constants, "    'IS_LONG' => %lld,\n", (long long)(IS_LONG));
#endif
#ifdef IS_DOUBLE
    fprintf(constants, "    'IS_DOUBLE' => %lld,\n", (long long)(IS_DOUBLE));
#endif
#ifdef IS_STRING
    fprintf(constants, "    'IS_STRING' => %lld,\n", (long long)(IS_STRING));
#endif
#ifdef IS_ARRAY
    fprintf(constants, "    'IS_ARRAY' => %lld,\n", (long long)(IS_ARRAY));
#endif
#ifdef IS_OBJECT
    fprintf(constants, "    'IS_OBJECT' => %lld,\n", (long long)(IS_OBJECT));
#endif
#ifdef IS_RESOURCE
    fprintf(constants, "    'IS_RESOURCE' => %lld,\n", (long long)(IS_RESOURCE));
#endif
#ifdef IS_REFERENCE
    fprintf(constants, "    'IS_REFERENCE' => %lld,\n", (long long)(IS_REFERENCE));
#endif
#ifdef IS_CONSTANT_AST
    fprintf(constants, "    'IS_CONSTANT_AST' => %lld,\n", (long long)(IS_CONSTANT_AST));
#endif
#ifdef IS_CALLABLE
    fprintf(constants, "    'IS_CALLABLE' => %lld,\n", (long long)(IS_CALLABLE));
#endif
#ifdef IS_ITERABLE
    fprintf(constants, "    'IS_ITERABLE' => %lld,\n", (long long)(IS_ITERABLE));
#endif
#ifdef IS_VOID
    fprintf(constants, "    'IS_VOID' => %lld,\n", (long long)(IS_VOID));
#endif
#ifdef IS_STATIC
    fprintf(constants, "    'IS_STATIC' => %lld,\n", (long long)(IS_STATIC));
#endif
#ifdef IS_MIXED
    fprintf(constants, "    'IS_MIXED' => %lld,\n", (long long)(IS_MIXED));
#endif
#ifdef IS_NEVER
    fprintf(constants, "    'IS_NEVER' => %lld,\n", (long long)(IS_NEVER));
#endif
#ifdef IS_INDIRECT
    fprintf(constants, "    'IS_INDIRECT' => %lld,\n", (long long)(IS_INDIRECT));
#endif
#ifdef IS_PTR
    fprintf(constants, "    'IS_PTR' => %lld,\n", (long long)(IS_PTR));
#endif
#ifdef IS_ALIAS_PTR
    fprintf(constants, "    'IS_ALIAS_PTR' => %lld,\n", (long long)(IS_ALIAS_PTR));
#endif
#ifdef _IS_ERROR
    fprintf(constants, "    '_IS_ERROR' => %lld,\n", (long long)(_IS_ERROR));
#endif
#ifdef _IS_BOOL
    fprintf(constants, "    '_IS_BOOL' => %lld,\n", (long long)(_IS_BOOL));
#endif
#ifdef _IS_NUMBER
    fprintf(constants, "    '_IS_NUMBER' => %lld,\n", (long long)(_IS_NUMBER));
#endif
#ifdef IS_TYPE_REFCOUNTED
    fprintf(constants, "    'IS_TYPE_REFCOUNTED' => %lld,\n", (long long)(IS_TYPE_REFCOUNTED));
#endif
#ifdef IS_TYPE_COLLECTABLE
    fprintf(constants, "    'IS_TYPE_COLLECTABLE' => %lld,\n", (long long)(IS_TYPE_COLLECTABLE));
#endif
#ifdef Z_TYPE_MASK
    fprintf(constants, "    'Z_TYPE_MASK' => %lld,\n", (long long)(Z_TYPE_MASK));
#endif
#ifdef Z_TYPE_FLAGS_MASK
    fprintf(constants, "    'Z_TYPE_FLAGS_MASK' => %lld,\n", (long long)(Z_TYPE_FLAGS_MASK));
#endif
#ifdef Z_TYPE_FLAGS_SHIFT
    fprintf(constants, "    'Z_TYPE_FLAGS_SHIFT' => %lld,\n", (long long)(Z_TYPE_FLAGS_SHIFT));
#endif
#ifdef GC_TYPE_MASK
    fprintf(constants, "    'GC_TYPE_MASK' => %lld,\n", (long long)(GC_TYPE_MASK));
#endif
#ifdef GC_FLAGS_MASK
    fprintf(constants, "    'GC_FLAGS_MASK' => %lld,\n", (long long)(GC_FLAGS_MASK));
#endif
#ifdef GC_INFO_MASK
    fprintf(constants, "    'GC_INFO_MASK' => %lld,\n", (long long)(GC_INFO_MASK));
#endif
#ifdef GC_FLAGS_SHIFT
    fprintf(constants, "    'GC_FLAGS_SHIFT' => %lld,\n", (long long)(GC_FLAGS_SHIFT));
#endif
#ifdef GC_INFO_SHIFT
    fprintf(constants, "    'GC_INFO_SHIFT' => %lld,\n", (long long)(GC_INFO_SHIFT));
#endif
#ifdef GC_NULL
    fprintf(constants, "    'GC_NULL' => %lld,\n", (long long)(GC_NULL));
#endif
#ifdef GC_STRING
    fprintf(constants, "    'GC_STRING' => %lld,\n", (long long)(GC_STRING));
#endif
#ifdef GC_ARRAY
    fprintf(constants, "    'GC_ARRAY' => %lld,\n", (long long)(GC_ARRAY));
#endif
#ifdef GC_OBJECT
    fprintf(constants, "    'GC_OBJECT' => %lld,\n", (long long)(GC_OBJECT));
#endif
#ifdef GC_RESOURCE
    fprintf(constants, "    'GC_RESOURCE' => %lld,\n", (long long)(GC_RESOURCE));
#endif
#ifdef GC_REFERENCE
    fprintf(constants, "    'GC_REFERENCE' => %lld,\n", (long long)(GC_REFERENCE));
#endif
#ifdef GC_CONSTANT_AST
    fprintf(constants, "    'GC_CONSTANT_AST' => %lld,\n", (long long)(GC_CONSTANT_AST));
#endif
#ifdef GC_NOT_COLLECTABLE
    fprintf(constants, "    'GC_NOT_COLLECTABLE' => %lld,\n", (long long)(GC_NOT_COLLECTABLE));
#endif
#ifdef GC_PROTECTED
    fprintf(constants, "    'GC_PROTECTED' => %lld,\n", (long long)(GC_PROTECTED));
#endif
#ifdef GC_IMMUTABLE
    fprintf(constants, "    'GC_IMMUTABLE' => %lld,\n", (long long)(GC_IMMUTABLE));
#endif
#ifdef GC_PERSISTENT
    fprintf(constants, "    'GC_PERSISTENT' => %lld,\n", (long long)(GC_PERSISTENT));
#endif
#ifdef GC_PERSISTENT_LOCAL
    fprintf(constants, "    'GC_PERSISTENT_LOCAL' => %lld,\n", (long long)(GC_PERSISTENT_LOCAL));
#endif
#ifdef IS_STR_CLASS_NAME_MAP_PTR
    fprintf(constants, "    'IS_STR_CLASS_NAME_MAP_PTR' => %lld,\n", (long long)(IS_STR_CLASS_NAME_MAP_PTR));
#endif
#ifdef IS_STR_INTERNED
    fprintf(constants, "    'IS_STR_INTERNED' => %lld,\n", (long long)(IS_STR_INTERNED));
#endif
#ifdef IS_STR_PERSISTENT
    fprintf(constants, "    'IS_STR_PERSISTENT' => %lld,\n", (long long)(IS_STR_PERSISTENT));
#endif
#ifdef IS_STR_PERMANENT
    fprintf(constants, "    'IS_STR_PERMANENT' => %lld,\n", (long long)(IS_STR_PERMANENT));
#endif
#ifdef IS_STR_VALID_UTF8
    fprintf(constants, "    'IS_STR_VALID_UTF8' => %lld,\n", (long long)(IS_STR_VALID_UTF8));
#endif
#ifdef IS_ARRAY_IMMUTABLE
    fprintf(constants, "    'IS_ARRAY_IMMUTABLE' => %lld,\n", (long long)(IS_ARRAY_IMMUTABLE));
#endif
#ifdef IS_ARRAY_PERSISTENT
    fprintf(constants, "    'IS_ARRAY_PERSISTENT' => %lld,\n", (long long)(IS_ARRAY_PERSISTENT));
#endif
#ifdef IS_OBJ_WEAKLY_REFERENCED
    fprintf(constants, "    'IS_OBJ_WEAKLY_REFERENCED' => %lld,\n", (long long)(IS_OBJ_WEAKLY_REFERENCED));
#endif
#ifdef IS_OBJ_DESTRUCTOR_CALLED
    fprintf(constants, "    'IS_OBJ_DESTRUCTOR_CALLED' => %lld,\n", (long long)(IS_OBJ_DESTRUCTOR_CALLED));
#endif
#ifdef IS_OBJ_FREE_CALLED
    fprintf(constants, "    'IS_OBJ_FREE_CALLED' => %lld,\n", (long long)(IS_OBJ_FREE_CALLED));
#endif
#ifdef IS_OBJ_LAZY_UNINITIALIZED
    fprintf(constants, "    'IS_OBJ_LAZY_UNINITIALIZED' => %lld,\n", (long long)(IS_OBJ_LAZY_UNINITIALIZED));
#endif
#ifdef IS_OBJ_LAZY_PROXY
    fprintf(constants, "    'IS_OBJ_LAZY_PROXY' => %lld,\n", (long long)(IS_OBJ_LAZY_PROXY));
#endif
#ifdef HASH_FLAG_CONSISTENCY
    fprintf(constants, "    'HASH_FLAG_CONSISTENCY' => %lld,\n", (long long)(HASH_FLAG_CONSISTENCY));
#endif
#ifdef HASH_FLAG_PACKED
    fprintf(constants, "    'HASH_FLAG_PACKED' => %lld,\n", (long long)(HASH_FLAG_PACKED));
#endif
#ifdef HASH_FLAG_UNINITIALIZED
    fprintf(constants, "    'HASH_FLAG_UNINITIALIZED' => %lld,\n", (long long)(HASH_FLAG_UNINITIALIZED));
#endif
#ifdef HASH_FLAG_STATIC_KEYS
    fprintf(constants, "    'HASH_FLAG_STATIC_KEYS' => %lld,\n", (long long)(HASH_FLAG_STATIC_KEYS));
#endif
#ifdef HASH_FLAG_HAS_EMPTY_IND
    fprintf(constants, "    'HASH_FLAG_HAS_EMPTY_IND' => %lld,\n", (long long)(HASH_FLAG_HAS_EMPTY_IND));
#endif
#ifdef HASH_FLAG_ALLOW_COW_VIOLATION
    fprintf(constants, "    'HASH_FLAG_ALLOW_COW_VIOLATION' => %lld,\n", (long long)(HASH_FLAG_ALLOW_COW_VIOLATION));
#endif
#ifdef HASH_UPDATE
    fprintf(constants, "    'HASH_UPDATE' => %lld,\n", (long long)(HASH_UPDATE));
#endif
#ifdef HASH_ADD
    fprintf(constants, "    'HASH_ADD' => %lld,\n", (long long)(HASH_ADD));
#endif
#ifdef HASH_UPDATE_INDIRECT
    fprintf(constants, "    'HASH_UPDATE_INDIRECT' => %lld,\n", (long long)(HASH_UPDATE_INDIRECT));
#endif
#ifdef HASH_ADD_NEW
    fprintf(constants, "    'HASH_ADD_NEW' => %lld,\n", (long long)(HASH_ADD_NEW));
#endif
#ifdef HASH_ADD_NEXT
    fprintf(constants, "    'HASH_ADD_NEXT' => %lld,\n", (long long)(HASH_ADD_NEXT));
#endif
#ifdef HT_MIN_MASK
    fprintf(constants, "    'HT_MIN_MASK' => %lld,\n", (long long)(HT_MIN_MASK));
#endif
#ifdef HT_MIN_SIZE
    fprintf(constants, "    'HT_MIN_SIZE' => %lld,\n", (long long)(HT_MIN_SIZE));
#endif
#ifdef ZEND_MODULE_API_NO
    fprintf(constants, "    'ZEND_MODULE_API_NO' => %lld,\n", (long long)(ZEND_MODULE_API_NO));
#endif
#ifdef MODULE_PERSISTENT
    fprintf(constants, "    'MODULE_PERSISTENT' => %lld,\n", (long long)(MODULE_PERSISTENT));
#endif
#ifdef MODULE_TEMPORARY
    fprintf(constants, "    'MODULE_TEMPORARY' => %lld,\n", (long long)(MODULE_TEMPORARY));
#endif
#ifdef CONST_CS
    fprintf(constants, "    'CONST_CS' => %lld,\n", (long long)(CONST_CS));
#endif
#ifdef CONST_PERSISTENT
    fprintf(constants, "    'CONST_PERSISTENT' => %lld,\n", (long long)(CONST_PERSISTENT));
#endif
#ifdef CONST_NO_FILE_CACHE
    fprintf(constants, "    'CONST_NO_FILE_CACHE' => %lld,\n", (long long)(CONST_NO_FILE_CACHE));
#endif
#ifdef CONST_DEPRECATED
    fprintf(constants, "    'CONST_DEPRECATED' => %lld,\n", (long long)(CONST_DEPRECATED));
#endif
#ifdef CONST_OWNED
    fprintf(constants, "    'CONST_OWNED' => %lld,\n", (long long)(CONST_OWNED));
#endif
#ifdef CONST_RECURSIVE
    fprintf(constants, "    'CONST_RECURSIVE' => %lld,\n", (long long)(CONST_RECURSIVE));
#endif
#ifdef PHP_USER_CONSTANT
    fprintf(constants, "    'PHP_USER_CONSTANT' => %lld,\n", (long long)(PHP_USER_CONSTANT));
#endif
#ifdef ZEND_DEBUG
    fprintf(constants, "    'ZEND_DEBUG' => %lld,\n", (long long)(ZEND_DEBUG));
#endif
#ifdef ZEND_MM_ALIGNMENT
    fprintf(constants, "    'ZEND_MM_ALIGNMENT' => %lld,\n", (long long)(ZEND_MM_ALIGNMENT));
#endif
#ifdef ZEND_MAX_RESERVED_RESOURCES
    fprintf(constants, "    'ZEND_MAX_RESERVED_RESOURCES' => %lld,\n", (long long)(ZEND_MAX_RESERVED_RESOURCES));
#endif
#ifdef ZEND_INTERNAL_FUNCTION
    fprintf(constants, "    'ZEND_INTERNAL_FUNCTION' => %lld,\n", (long long)(ZEND_INTERNAL_FUNCTION));
#endif
#ifdef ZEND_USER_FUNCTION
    fprintf(constants, "    'ZEND_USER_FUNCTION' => %lld,\n", (long long)(ZEND_USER_FUNCTION));
#endif
#ifdef ZEND_EVAL_CODE
    fprintf(constants, "    'ZEND_EVAL_CODE' => %lld,\n", (long long)(ZEND_EVAL_CODE));
#endif
#ifdef ZEND_COMPILE_EXTENDED_STMT
    fprintf(constants, "    'ZEND_COMPILE_EXTENDED_STMT' => %lld,\n", (long long)(ZEND_COMPILE_EXTENDED_STMT));
#endif
#ifdef ZEND_COMPILE_EXTENDED_FCALL
    fprintf(constants, "    'ZEND_COMPILE_EXTENDED_FCALL' => %lld,\n", (long long)(ZEND_COMPILE_EXTENDED_FCALL));
#endif
#ifdef ZEND_COMPILE_EXTENDED_INFO
    fprintf(constants, "    'ZEND_COMPILE_EXTENDED_INFO' => %lld,\n", (long long)(ZEND_COMPILE_EXTENDED_INFO));
#endif
#ifdef ZEND_COMPILE_HANDLE_OP_ARRAY
    fprintf(constants, "    'ZEND_COMPILE_HANDLE_OP_ARRAY' => %lld,\n", (long long)(ZEND_COMPILE_HANDLE_OP_ARRAY));
#endif
#ifdef ZEND_COMPILE_IGNORE_INTERNAL_FUNCTIONS
    fprintf(constants, "    'ZEND_COMPILE_IGNORE_INTERNAL_FUNCTIONS' => %lld,\n", (long long)(ZEND_COMPILE_IGNORE_INTERNAL_FUNCTIONS));
#endif
#ifdef ZEND_COMPILE_DELAYED_BINDING
    fprintf(constants, "    'ZEND_COMPILE_DELAYED_BINDING' => %lld,\n", (long long)(ZEND_COMPILE_DELAYED_BINDING));
#endif
#ifdef ZEND_COMPILE_NO_CONSTANT_SUBSTITUTION
    fprintf(constants, "    'ZEND_COMPILE_NO_CONSTANT_SUBSTITUTION' => %lld,\n", (long long)(ZEND_COMPILE_NO_CONSTANT_SUBSTITUTION));
#endif
#ifdef ZEND_COMPILE_IGNORE_INTERNAL_CLASSES
    fprintf(constants, "    'ZEND_COMPILE_IGNORE_INTERNAL_CLASSES' => %lld,\n", (long long)(ZEND_COMPILE_IGNORE_INTERNAL_CLASSES));
#endif
#ifdef ZEND_COMPILE_IGNORE_USER_FUNCTIONS
    fprintf(constants, "    'ZEND_COMPILE_IGNORE_USER_FUNCTIONS' => %lld,\n", (long long)(ZEND_COMPILE_IGNORE_USER_FUNCTIONS));
#endif
#ifdef ZEND_COMPILE_GUARDS
    fprintf(constants, "    'ZEND_COMPILE_GUARDS' => %lld,\n", (long long)(ZEND_COMPILE_GUARDS));
#endif
#ifdef ZEND_COMPILE_NO_BUILTINS
    fprintf(constants, "    'ZEND_COMPILE_NO_BUILTINS' => %lld,\n", (long long)(ZEND_COMPILE_NO_BUILTINS));
#endif
#ifdef ZEND_COMPILE_NO_JUMPTABLES
    fprintf(constants, "    'ZEND_COMPILE_NO_JUMPTABLES' => %lld,\n", (long long)(ZEND_COMPILE_NO_JUMPTABLES));
#endif
#ifdef ZEND_COMPILE_PRELOAD
    fprintf(constants, "    'ZEND_COMPILE_PRELOAD' => %lld,\n", (long long)(ZEND_COMPILE_PRELOAD));
#endif
#ifdef ZEND_COMPILE_PRELOAD_IN_CHILD
    fprintf(constants, "    'ZEND_COMPILE_PRELOAD_IN_CHILD' => %lld,\n", (long long)(ZEND_COMPILE_PRELOAD_IN_CHILD));
#endif
#ifdef ZEND_COMPILE_WITHOUT_EXECUTION
    fprintf(constants, "    'ZEND_COMPILE_WITHOUT_EXECUTION' => %lld,\n", (long long)(ZEND_COMPILE_WITHOUT_EXECUTION));
#endif
#ifdef ZEND_CALL_FUNCTION
    fprintf(constants, "    'ZEND_CALL_FUNCTION' => %lld,\n", (long long)(ZEND_CALL_FUNCTION));
#endif
#ifdef ZEND_CALL_CODE
    fprintf(constants, "    'ZEND_CALL_CODE' => %lld,\n", (long long)(ZEND_CALL_CODE));
#endif
#ifdef ZEND_CALL_NESTED
    fprintf(constants, "    'ZEND_CALL_NESTED' => %lld,\n", (long long)(ZEND_CALL_NESTED));
#endif
#ifdef ZEND_CALL_TOP
    fprintf(constants, "    'ZEND_CALL_TOP' => %lld,\n", (long long)(ZEND_CALL_TOP));
#endif
#ifdef ZEND_CALL_HAS_THIS
    fprintf(constants, "    'ZEND_CALL_HAS_THIS' => %lld,\n", (long long)(ZEND_CALL_HAS_THIS));
#endif
#ifdef ZEND_CALL_FAKE_CLOSURE
    fprintf(constants, "    'ZEND_CALL_FAKE_CLOSURE' => %lld,\n", (long long)(ZEND_CALL_FAKE_CLOSURE));
#endif
#ifdef ZEND_CALL_CLOSURE
    fprintf(constants, "    'ZEND_CALL_CLOSURE' => %lld,\n", (long long)(ZEND_CALL_CLOSURE));
#endif
#ifdef ZEND_CALL_HAS_SYMBOL_TABLE
    fprintf(constants, "    'ZEND_CALL_HAS_SYMBOL_TABLE' => %lld,\n", (long long)(ZEND_CALL_HAS_SYMBOL_TABLE));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_CLASS
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_CLASS' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_CLASS));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_FUNCTION
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_FUNCTION' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_FUNCTION));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_METHOD
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_METHOD' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_METHOD));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_PROPERTY
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_PROPERTY' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_PROPERTY));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_CLASS_CONST
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_CLASS_CONST' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_CLASS_CONST));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_PARAMETER
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_PARAMETER' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_PARAMETER));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_CONST
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_CONST' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_CONST));
#endif
#ifdef ZEND_ATTRIBUTE_TARGET_ALL
    fprintf(constants, "    'ZEND_ATTRIBUTE_TARGET_ALL' => %lld,\n", (long long)(ZEND_ATTRIBUTE_TARGET_ALL));
#endif
#ifdef ZEND_ATTRIBUTE_IS_REPEATABLE
    fprintf(constants, "    'ZEND_ATTRIBUTE_IS_REPEATABLE' => %lld,\n", (long long)(ZEND_ATTRIBUTE_IS_REPEATABLE));
#endif
#ifdef ZEND_ATTRIBUTE_FLAGS
    fprintf(constants, "    'ZEND_ATTRIBUTE_FLAGS' => %lld,\n", (long long)(ZEND_ATTRIBUTE_FLAGS));
#endif
    fprintf(constants, "    'ZEND_AST_ZVAL' => %lld,\n", (long long)(ZEND_AST_ZVAL));
    fprintf(constants, "    'ZEND_AST_CONSTANT' => %lld,\n", (long long)(ZEND_AST_CONSTANT));
    fprintf(constants, "    'ZEND_AST_ZNODE' => %lld,\n", (long long)(ZEND_AST_ZNODE));
    fprintf(constants, "    'ZEND_AST_FUNC_DECL' => %lld,\n", (long long)(ZEND_AST_FUNC_DECL));
    fprintf(constants, "    'ZEND_AST_CLOSURE' => %lld,\n", (long long)(ZEND_AST_CLOSURE));
    fprintf(constants, "    'ZEND_AST_METHOD' => %lld,\n", (long long)(ZEND_AST_METHOD));
    fprintf(constants, "    'ZEND_AST_CLASS' => %lld,\n", (long long)(ZEND_AST_CLASS));
    fprintf(constants, "    'ZEND_AST_ARROW_FUNC' => %lld,\n", (long long)(ZEND_AST_ARROW_FUNC));
    fprintf(constants, "    'ZEND_AST_PROPERTY_HOOK' => %lld,\n", (long long)(ZEND_AST_PROPERTY_HOOK));
    fprintf(constants, "    'ZEND_AST_ARG_LIST' => %lld,\n", (long long)(ZEND_AST_ARG_LIST));
    fprintf(constants, "    'ZEND_AST_ARRAY' => %lld,\n", (long long)(ZEND_AST_ARRAY));
    fprintf(constants, "    'ZEND_AST_ENCAPS_LIST' => %lld,\n", (long long)(ZEND_AST_ENCAPS_LIST));
    fprintf(constants, "    'ZEND_AST_EXPR_LIST' => %lld,\n", (long long)(ZEND_AST_EXPR_LIST));
    fprintf(constants, "    'ZEND_AST_STMT_LIST' => %lld,\n", (long long)(ZEND_AST_STMT_LIST));
    fprintf(constants, "    'ZEND_AST_IF' => %lld,\n", (long long)(ZEND_AST_IF));
    fprintf(constants, "    'ZEND_AST_SWITCH_LIST' => %lld,\n", (long long)(ZEND_AST_SWITCH_LIST));
    fprintf(constants, "    'ZEND_AST_CATCH_LIST' => %lld,\n", (long long)(ZEND_AST_CATCH_LIST));
    fprintf(constants, "    'ZEND_AST_PARAM_LIST' => %lld,\n", (long long)(ZEND_AST_PARAM_LIST));
    fprintf(constants, "    'ZEND_AST_CLOSURE_USES' => %lld,\n", (long long)(ZEND_AST_CLOSURE_USES));
    fprintf(constants, "    'ZEND_AST_PROP_DECL' => %lld,\n", (long long)(ZEND_AST_PROP_DECL));
    fprintf(constants, "    'ZEND_AST_CONST_DECL' => %lld,\n", (long long)(ZEND_AST_CONST_DECL));
    fprintf(constants, "    'ZEND_AST_CLASS_CONST_DECL' => %lld,\n", (long long)(ZEND_AST_CLASS_CONST_DECL));
    fprintf(constants, "    'ZEND_AST_NAME_LIST' => %lld,\n", (long long)(ZEND_AST_NAME_LIST));
    fprintf(constants, "    'ZEND_AST_TRAIT_ADAPTATIONS' => %lld,\n", (long long)(ZEND_AST_TRAIT_ADAPTATIONS));
    fprintf(constants, "    'ZEND_AST_USE' => %lld,\n", (long long)(ZEND_AST_USE));
    fprintf(constants, "    'ZEND_AST_TYPE_UNION' => %lld,\n", (long long)(ZEND_AST_TYPE_UNION));
    fprintf(constants, "    'ZEND_AST_TYPE_INTERSECTION' => %lld,\n", (long long)(ZEND_AST_TYPE_INTERSECTION));
    fprintf(constants, "    'ZEND_AST_ATTRIBUTE_LIST' => %lld,\n", (long long)(ZEND_AST_ATTRIBUTE_LIST));
    fprintf(constants, "    'ZEND_AST_ATTRIBUTE_GROUP' => %lld,\n", (long long)(ZEND_AST_ATTRIBUTE_GROUP));
    fprintf(constants, "    'ZEND_AST_MATCH_ARM_LIST' => %lld,\n", (long long)(ZEND_AST_MATCH_ARM_LIST));
    fprintf(constants, "    'ZEND_AST_MODIFIER_LIST' => %lld,\n", (long long)(ZEND_AST_MODIFIER_LIST));
    fprintf(constants, "    'ZEND_AST_MAGIC_CONST' => %lld,\n", (long long)(ZEND_AST_MAGIC_CONST));
    fprintf(constants, "    'ZEND_AST_TYPE' => %lld,\n", (long long)(ZEND_AST_TYPE));
    fprintf(constants, "    'ZEND_AST_CONSTANT_CLASS' => %lld,\n", (long long)(ZEND_AST_CONSTANT_CLASS));
    fprintf(constants, "    'ZEND_AST_CALLABLE_CONVERT' => %lld,\n", (long long)(ZEND_AST_CALLABLE_CONVERT));
    fprintf(constants, "    'ZEND_AST_VAR' => %lld,\n", (long long)(ZEND_AST_VAR));
    fprintf(constants, "    'ZEND_AST_CONST' => %lld,\n", (long long)(ZEND_AST_CONST));
    fprintf(constants, "    'ZEND_AST_UNPACK' => %lld,\n", (long long)(ZEND_AST_UNPACK));
    fprintf(constants, "    'ZEND_AST_UNARY_PLUS' => %lld,\n", (long long)(ZEND_AST_UNARY_PLUS));
    fprintf(constants, "    'ZEND_AST_UNARY_MINUS' => %lld,\n", (long long)(ZEND_AST_UNARY_MINUS));
    fprintf(constants, "    'ZEND_AST_CAST' => %lld,\n", (long long)(ZEND_AST_CAST));
    fprintf(constants, "    'ZEND_AST_EMPTY' => %lld,\n", (long long)(ZEND_AST_EMPTY));
    fprintf(constants, "    'ZEND_AST_ISSET' => %lld,\n", (long long)(ZEND_AST_ISSET));
    fprintf(constants, "    'ZEND_AST_SILENCE' => %lld,\n", (long long)(ZEND_AST_SILENCE));
    fprintf(constants, "    'ZEND_AST_SHELL_EXEC' => %lld,\n", (long long)(ZEND_AST_SHELL_EXEC));
    fprintf(constants, "    'ZEND_AST_CLONE' => %lld,\n", (long long)(ZEND_AST_CLONE));
    fprintf(constants, "    'ZEND_AST_EXIT' => %lld,\n", (long long)(ZEND_AST_EXIT));
    fprintf(constants, "    'ZEND_AST_PRINT' => %lld,\n", (long long)(ZEND_AST_PRINT));
    fprintf(constants, "    'ZEND_AST_INCLUDE_OR_EVAL' => %lld,\n", (long long)(ZEND_AST_INCLUDE_OR_EVAL));
    fprintf(constants, "    'ZEND_AST_UNARY_OP' => %lld,\n", (long long)(ZEND_AST_UNARY_OP));
    fprintf(constants, "    'ZEND_AST_PRE_INC' => %lld,\n", (long long)(ZEND_AST_PRE_INC));
    fprintf(constants, "    'ZEND_AST_PRE_DEC' => %lld,\n", (long long)(ZEND_AST_PRE_DEC));
    fprintf(constants, "    'ZEND_AST_POST_INC' => %lld,\n", (long long)(ZEND_AST_POST_INC));
    fprintf(constants, "    'ZEND_AST_POST_DEC' => %lld,\n", (long long)(ZEND_AST_POST_DEC));
    fprintf(constants, "    'ZEND_AST_YIELD_FROM' => %lld,\n", (long long)(ZEND_AST_YIELD_FROM));
    fprintf(constants, "    'ZEND_AST_CLASS_NAME' => %lld,\n", (long long)(ZEND_AST_CLASS_NAME));
    fprintf(constants, "    'ZEND_AST_GLOBAL' => %lld,\n", (long long)(ZEND_AST_GLOBAL));
    fprintf(constants, "    'ZEND_AST_UNSET' => %lld,\n", (long long)(ZEND_AST_UNSET));
    fprintf(constants, "    'ZEND_AST_RETURN' => %lld,\n", (long long)(ZEND_AST_RETURN));
    fprintf(constants, "    'ZEND_AST_LABEL' => %lld,\n", (long long)(ZEND_AST_LABEL));
    fprintf(constants, "    'ZEND_AST_REF' => %lld,\n", (long long)(ZEND_AST_REF));
    fprintf(constants, "    'ZEND_AST_HALT_COMPILER' => %lld,\n", (long long)(ZEND_AST_HALT_COMPILER));
    fprintf(constants, "    'ZEND_AST_ECHO' => %lld,\n", (long long)(ZEND_AST_ECHO));
    fprintf(constants, "    'ZEND_AST_THROW' => %lld,\n", (long long)(ZEND_AST_THROW));
    fprintf(constants, "    'ZEND_AST_GOTO' => %lld,\n", (long long)(ZEND_AST_GOTO));
    fprintf(constants, "    'ZEND_AST_BREAK' => %lld,\n", (long long)(ZEND_AST_BREAK));
    fprintf(constants, "    'ZEND_AST_CONTINUE' => %lld,\n", (long long)(ZEND_AST_CONTINUE));
    fprintf(constants, "    'ZEND_AST_PROPERTY_HOOK_SHORT_BODY' => %lld,\n", (long long)(ZEND_AST_PROPERTY_HOOK_SHORT_BODY));
    fprintf(constants, "    'ZEND_AST_DIM' => %lld,\n", (long long)(ZEND_AST_DIM));
    fprintf(constants, "    'ZEND_AST_PROP' => %lld,\n", (long long)(ZEND_AST_PROP));
    fprintf(constants, "    'ZEND_AST_NULLSAFE_PROP' => %lld,\n", (long long)(ZEND_AST_NULLSAFE_PROP));
    fprintf(constants, "    'ZEND_AST_STATIC_PROP' => %lld,\n", (long long)(ZEND_AST_STATIC_PROP));
    fprintf(constants, "    'ZEND_AST_CALL' => %lld,\n", (long long)(ZEND_AST_CALL));
    fprintf(constants, "    'ZEND_AST_CLASS_CONST' => %lld,\n", (long long)(ZEND_AST_CLASS_CONST));
    fprintf(constants, "    'ZEND_AST_ASSIGN' => %lld,\n", (long long)(ZEND_AST_ASSIGN));
    fprintf(constants, "    'ZEND_AST_ASSIGN_REF' => %lld,\n", (long long)(ZEND_AST_ASSIGN_REF));
    fprintf(constants, "    'ZEND_AST_ASSIGN_OP' => %lld,\n", (long long)(ZEND_AST_ASSIGN_OP));
    fprintf(constants, "    'ZEND_AST_BINARY_OP' => %lld,\n", (long long)(ZEND_AST_BINARY_OP));
    fprintf(constants, "    'ZEND_AST_GREATER' => %lld,\n", (long long)(ZEND_AST_GREATER));
    fprintf(constants, "    'ZEND_AST_GREATER_EQUAL' => %lld,\n", (long long)(ZEND_AST_GREATER_EQUAL));
    fprintf(constants, "    'ZEND_AST_AND' => %lld,\n", (long long)(ZEND_AST_AND));
    fprintf(constants, "    'ZEND_AST_OR' => %lld,\n", (long long)(ZEND_AST_OR));
    fprintf(constants, "    'ZEND_AST_ARRAY_ELEM' => %lld,\n", (long long)(ZEND_AST_ARRAY_ELEM));
    fprintf(constants, "    'ZEND_AST_NEW' => %lld,\n", (long long)(ZEND_AST_NEW));
    fprintf(constants, "    'ZEND_AST_INSTANCEOF' => %lld,\n", (long long)(ZEND_AST_INSTANCEOF));
    fprintf(constants, "    'ZEND_AST_YIELD' => %lld,\n", (long long)(ZEND_AST_YIELD));
    fprintf(constants, "    'ZEND_AST_COALESCE' => %lld,\n", (long long)(ZEND_AST_COALESCE));
    fprintf(constants, "    'ZEND_AST_ASSIGN_COALESCE' => %lld,\n", (long long)(ZEND_AST_ASSIGN_COALESCE));
    fprintf(constants, "    'ZEND_AST_STATIC' => %lld,\n", (long long)(ZEND_AST_STATIC));
    fprintf(constants, "    'ZEND_AST_WHILE' => %lld,\n", (long long)(ZEND_AST_WHILE));
    fprintf(constants, "    'ZEND_AST_DO_WHILE' => %lld,\n", (long long)(ZEND_AST_DO_WHILE));
    fprintf(constants, "    'ZEND_AST_IF_ELEM' => %lld,\n", (long long)(ZEND_AST_IF_ELEM));
    fprintf(constants, "    'ZEND_AST_SWITCH' => %lld,\n", (long long)(ZEND_AST_SWITCH));
    fprintf(constants, "    'ZEND_AST_SWITCH_CASE' => %lld,\n", (long long)(ZEND_AST_SWITCH_CASE));
    fprintf(constants, "    'ZEND_AST_DECLARE' => %lld,\n", (long long)(ZEND_AST_DECLARE));
    fprintf(constants, "    'ZEND_AST_USE_TRAIT' => %lld,\n", (long long)(ZEND_AST_USE_TRAIT));
    fprintf(constants, "    'ZEND_AST_TRAIT_PRECEDENCE' => %lld,\n", (long long)(ZEND_AST_TRAIT_PRECEDENCE));
    fprintf(constants, "    'ZEND_AST_METHOD_REFERENCE' => %lld,\n", (long long)(ZEND_AST_METHOD_REFERENCE));
    fprintf(constants, "    'ZEND_AST_NAMESPACE' => %lld,\n", (long long)(ZEND_AST_NAMESPACE));
    fprintf(constants, "    'ZEND_AST_USE_ELEM' => %lld,\n", (long long)(ZEND_AST_USE_ELEM));
    fprintf(constants, "    'ZEND_AST_TRAIT_ALIAS' => %lld,\n", (long long)(ZEND_AST_TRAIT_ALIAS));
    fprintf(constants, "    'ZEND_AST_GROUP_USE' => %lld,\n", (long long)(ZEND_AST_GROUP_USE));
    fprintf(constants, "    'ZEND_AST_ATTRIBUTE' => %lld,\n", (long long)(ZEND_AST_ATTRIBUTE));
    fprintf(constants, "    'ZEND_AST_MATCH' => %lld,\n", (long long)(ZEND_AST_MATCH));
    fprintf(constants, "    'ZEND_AST_MATCH_ARM' => %lld,\n", (long long)(ZEND_AST_MATCH_ARM));
    fprintf(constants, "    'ZEND_AST_NAMED_ARG' => %lld,\n", (long long)(ZEND_AST_NAMED_ARG));
    fprintf(constants, "    'ZEND_AST_PARENT_PROPERTY_HOOK_CALL' => %lld,\n", (long long)(ZEND_AST_PARENT_PROPERTY_HOOK_CALL));
    fprintf(constants, "    'ZEND_AST_METHOD_CALL' => %lld,\n", (long long)(ZEND_AST_METHOD_CALL));
    fprintf(constants, "    'ZEND_AST_NULLSAFE_METHOD_CALL' => %lld,\n", (long long)(ZEND_AST_NULLSAFE_METHOD_CALL));
    fprintf(constants, "    'ZEND_AST_STATIC_CALL' => %lld,\n", (long long)(ZEND_AST_STATIC_CALL));
    fprintf(constants, "    'ZEND_AST_CONDITIONAL' => %lld,\n", (long long)(ZEND_AST_CONDITIONAL));
    fprintf(constants, "    'ZEND_AST_TRY' => %lld,\n", (long long)(ZEND_AST_TRY));
    fprintf(constants, "    'ZEND_AST_CATCH' => %lld,\n", (long long)(ZEND_AST_CATCH));
    fprintf(constants, "    'ZEND_AST_PROP_GROUP' => %lld,\n", (long long)(ZEND_AST_PROP_GROUP));
    fprintf(constants, "    'ZEND_AST_CONST_ELEM' => %lld,\n", (long long)(ZEND_AST_CONST_ELEM));
    fprintf(constants, "    'ZEND_AST_CLASS_CONST_GROUP' => %lld,\n", (long long)(ZEND_AST_CLASS_CONST_GROUP));
    fprintf(constants, "    'ZEND_AST_CONST_ENUM_INIT' => %lld,\n", (long long)(ZEND_AST_CONST_ENUM_INIT));
    fprintf(constants, "    'ZEND_AST_FOR' => %lld,\n", (long long)(ZEND_AST_FOR));
    fprintf(constants, "    'ZEND_AST_FOREACH' => %lld,\n", (long long)(ZEND_AST_FOREACH));
    fprintf(constants, "    'ZEND_AST_ENUM_CASE' => %lld,\n", (long long)(ZEND_AST_ENUM_CASE));
    fprintf(constants, "    'ZEND_AST_PROP_ELEM' => %lld,\n", (long long)(ZEND_AST_PROP_ELEM));
    fprintf(constants, "    'ZEND_AST_PARAM' => %lld,\n", (long long)(ZEND_AST_PARAM));
    fprintf(constants, "    'ZEND_PROPERTY_HOOK_GET' => %lld,\n", (long long)(ZEND_PROPERTY_HOOK_GET));
    fprintf(constants, "    'ZEND_PROPERTY_HOOK_SET' => %lld,\n", (long long)(ZEND_PROPERTY_HOOK_SET));
    fprintf(constants, "    'ZEND_NOP' => 0,\n");
    fprintf(constants, "    'ZEND_ADD' => 1,\n");
    fprintf(constants, "    'ZEND_SUB' => 2,\n");
    fprintf(constants, "    'ZEND_MUL' => 3,\n");
    fprintf(constants, "    'ZEND_DIV' => 4,\n");
    fprintf(constants, "    'ZEND_MOD' => 5,\n");
    fprintf(constants, "    'ZEND_SL' => 6,\n");
    fprintf(constants, "    'ZEND_SR' => 7,\n");
    fprintf(constants, "    'ZEND_CONCAT' => 8,\n");
    fprintf(constants, "    'ZEND_BW_OR' => 9,\n");
    fprintf(constants, "    'ZEND_BW_AND' => 10,\n");
    fprintf(constants, "    'ZEND_BW_XOR' => 11,\n");
    fprintf(constants, "    'ZEND_POW' => 12,\n");
    fprintf(constants, "    'ZEND_BW_NOT' => 13,\n");
    fprintf(constants, "    'ZEND_BOOL_NOT' => 14,\n");
    fprintf(constants, "    'ZEND_BOOL_XOR' => 15,\n");
    fprintf(constants, "    'ZEND_IS_IDENTICAL' => 16,\n");
    fprintf(constants, "    'ZEND_IS_NOT_IDENTICAL' => 17,\n");
    fprintf(constants, "    'ZEND_IS_EQUAL' => 18,\n");
    fprintf(constants, "    'ZEND_IS_NOT_EQUAL' => 19,\n");
    fprintf(constants, "    'ZEND_IS_SMALLER' => 20,\n");
    fprintf(constants, "    'ZEND_IS_SMALLER_OR_EQUAL' => 21,\n");
    fprintf(constants, "    'ZEND_ASSIGN' => 22,\n");
    fprintf(constants, "    'ZEND_ASSIGN_DIM' => 23,\n");
    fprintf(constants, "    'ZEND_ASSIGN_OBJ' => 24,\n");
    fprintf(constants, "    'ZEND_ASSIGN_STATIC_PROP' => 25,\n");
    fprintf(constants, "    'ZEND_ASSIGN_OP' => 26,\n");
    fprintf(constants, "    'ZEND_ASSIGN_DIM_OP' => 27,\n");
    fprintf(constants, "    'ZEND_ASSIGN_OBJ_OP' => 28,\n");
    fprintf(constants, "    'ZEND_ASSIGN_STATIC_PROP_OP' => 29,\n");
    fprintf(constants, "    'ZEND_ASSIGN_REF' => 30,\n");
    fprintf(constants, "    'ZEND_QM_ASSIGN' => 31,\n");
    fprintf(constants, "    'ZEND_ASSIGN_OBJ_REF' => 32,\n");
    fprintf(constants, "    'ZEND_ASSIGN_STATIC_PROP_REF' => 33,\n");
    fprintf(constants, "    'ZEND_PRE_INC' => 34,\n");
    fprintf(constants, "    'ZEND_PRE_DEC' => 35,\n");
    fprintf(constants, "    'ZEND_POST_INC' => 36,\n");
    fprintf(constants, "    'ZEND_POST_DEC' => 37,\n");
    fprintf(constants, "    'ZEND_PRE_INC_STATIC_PROP' => 38,\n");
    fprintf(constants, "    'ZEND_PRE_DEC_STATIC_PROP' => 39,\n");
    fprintf(constants, "    'ZEND_POST_INC_STATIC_PROP' => 40,\n");
    fprintf(constants, "    'ZEND_POST_DEC_STATIC_PROP' => 41,\n");
    fprintf(constants, "    'ZEND_JMP' => 42,\n");
    fprintf(constants, "    'ZEND_JMPZ' => 43,\n");
    fprintf(constants, "    'ZEND_JMPNZ' => 44,\n");
    fprintf(constants, "    'ZEND_JMPZ_EX' => 46,\n");
    fprintf(constants, "    'ZEND_JMPNZ_EX' => 47,\n");
    fprintf(constants, "    'ZEND_CASE' => 48,\n");
    fprintf(constants, "    'ZEND_CHECK_VAR' => 49,\n");
    fprintf(constants, "    'ZEND_SEND_VAR_NO_REF_EX' => 50,\n");
    fprintf(constants, "    'ZEND_CAST' => 51,\n");
    fprintf(constants, "    'ZEND_BOOL' => 52,\n");
    fprintf(constants, "    'ZEND_FAST_CONCAT' => 53,\n");
    fprintf(constants, "    'ZEND_ROPE_INIT' => 54,\n");
    fprintf(constants, "    'ZEND_ROPE_ADD' => 55,\n");
    fprintf(constants, "    'ZEND_ROPE_END' => 56,\n");
    fprintf(constants, "    'ZEND_BEGIN_SILENCE' => 57,\n");
    fprintf(constants, "    'ZEND_END_SILENCE' => 58,\n");
    fprintf(constants, "    'ZEND_INIT_FCALL_BY_NAME' => 59,\n");
    fprintf(constants, "    'ZEND_DO_FCALL' => 60,\n");
    fprintf(constants, "    'ZEND_INIT_FCALL' => 61,\n");
    fprintf(constants, "    'ZEND_RETURN' => 62,\n");
    fprintf(constants, "    'ZEND_RECV' => 63,\n");
    fprintf(constants, "    'ZEND_RECV_INIT' => 64,\n");
    fprintf(constants, "    'ZEND_SEND_VAL' => 65,\n");
    fprintf(constants, "    'ZEND_SEND_VAR_EX' => 66,\n");
    fprintf(constants, "    'ZEND_SEND_REF' => 67,\n");
    fprintf(constants, "    'ZEND_NEW' => 68,\n");
    fprintf(constants, "    'ZEND_INIT_NS_FCALL_BY_NAME' => 69,\n");
    fprintf(constants, "    'ZEND_FREE' => 70,\n");
    fprintf(constants, "    'ZEND_INIT_ARRAY' => 71,\n");
    fprintf(constants, "    'ZEND_ADD_ARRAY_ELEMENT' => 72,\n");
    fprintf(constants, "    'ZEND_INCLUDE_OR_EVAL' => 73,\n");
    fprintf(constants, "    'ZEND_UNSET_VAR' => 74,\n");
    fprintf(constants, "    'ZEND_UNSET_DIM' => 75,\n");
    fprintf(constants, "    'ZEND_UNSET_OBJ' => 76,\n");
    fprintf(constants, "    'ZEND_FE_RESET_R' => 77,\n");
    fprintf(constants, "    'ZEND_FE_FETCH_R' => 78,\n");
    fprintf(constants, "    'ZEND_FETCH_R' => 80,\n");
    fprintf(constants, "    'ZEND_FETCH_DIM_R' => 81,\n");
    fprintf(constants, "    'ZEND_FETCH_OBJ_R' => 82,\n");
    fprintf(constants, "    'ZEND_FETCH_W' => 83,\n");
    fprintf(constants, "    'ZEND_FETCH_DIM_W' => 84,\n");
    fprintf(constants, "    'ZEND_FETCH_OBJ_W' => 85,\n");
    fprintf(constants, "    'ZEND_FETCH_RW' => 86,\n");
    fprintf(constants, "    'ZEND_FETCH_DIM_RW' => 87,\n");
    fprintf(constants, "    'ZEND_FETCH_OBJ_RW' => 88,\n");
    fprintf(constants, "    'ZEND_FETCH_IS' => 89,\n");
    fprintf(constants, "    'ZEND_FETCH_DIM_IS' => 90,\n");
    fprintf(constants, "    'ZEND_FETCH_OBJ_IS' => 91,\n");
    fprintf(constants, "    'ZEND_FETCH_FUNC_ARG' => 92,\n");
    fprintf(constants, "    'ZEND_FETCH_DIM_FUNC_ARG' => 93,\n");
    fprintf(constants, "    'ZEND_FETCH_OBJ_FUNC_ARG' => 94,\n");
    fprintf(constants, "    'ZEND_FETCH_UNSET' => 95,\n");
    fprintf(constants, "    'ZEND_FETCH_DIM_UNSET' => 96,\n");
    fprintf(constants, "    'ZEND_FETCH_OBJ_UNSET' => 97,\n");
    fprintf(constants, "    'ZEND_FETCH_LIST_R' => 98,\n");
    fprintf(constants, "    'ZEND_FETCH_CONSTANT' => 99,\n");
    fprintf(constants, "    'ZEND_CHECK_FUNC_ARG' => 100,\n");
    fprintf(constants, "    'ZEND_EXT_STMT' => 101,\n");
    fprintf(constants, "    'ZEND_EXT_FCALL_BEGIN' => 102,\n");
    fprintf(constants, "    'ZEND_EXT_FCALL_END' => 103,\n");
    fprintf(constants, "    'ZEND_EXT_NOP' => 104,\n");
    fprintf(constants, "    'ZEND_TICKS' => 105,\n");
    fprintf(constants, "    'ZEND_SEND_VAR_NO_REF' => 106,\n");
    fprintf(constants, "    'ZEND_CATCH' => 107,\n");
    fprintf(constants, "    'ZEND_THROW' => 108,\n");
    fprintf(constants, "    'ZEND_FETCH_CLASS' => 109,\n");
    fprintf(constants, "    'ZEND_CLONE' => 110,\n");
    fprintf(constants, "    'ZEND_RETURN_BY_REF' => 111,\n");
    fprintf(constants, "    'ZEND_INIT_METHOD_CALL' => 112,\n");
    fprintf(constants, "    'ZEND_INIT_STATIC_METHOD_CALL' => 113,\n");
    fprintf(constants, "    'ZEND_ISSET_ISEMPTY_VAR' => 114,\n");
    fprintf(constants, "    'ZEND_ISSET_ISEMPTY_DIM_OBJ' => 115,\n");
    fprintf(constants, "    'ZEND_SEND_VAL_EX' => 116,\n");
    fprintf(constants, "    'ZEND_SEND_VAR' => 117,\n");
    fprintf(constants, "    'ZEND_INIT_USER_CALL' => 118,\n");
    fprintf(constants, "    'ZEND_SEND_ARRAY' => 119,\n");
    fprintf(constants, "    'ZEND_SEND_USER' => 120,\n");
    fprintf(constants, "    'ZEND_STRLEN' => 121,\n");
    fprintf(constants, "    'ZEND_DEFINED' => 122,\n");
    fprintf(constants, "    'ZEND_TYPE_CHECK' => 123,\n");
    fprintf(constants, "    'ZEND_VERIFY_RETURN_TYPE' => 124,\n");
    fprintf(constants, "    'ZEND_FE_RESET_RW' => 125,\n");
    fprintf(constants, "    'ZEND_FE_FETCH_RW' => 126,\n");
    fprintf(constants, "    'ZEND_FE_FREE' => 127,\n");
    fprintf(constants, "    'ZEND_INIT_DYNAMIC_CALL' => 128,\n");
    fprintf(constants, "    'ZEND_DO_ICALL' => 129,\n");
    fprintf(constants, "    'ZEND_DO_UCALL' => 130,\n");
    fprintf(constants, "    'ZEND_DO_FCALL_BY_NAME' => 131,\n");
    fprintf(constants, "    'ZEND_PRE_INC_OBJ' => 132,\n");
    fprintf(constants, "    'ZEND_PRE_DEC_OBJ' => 133,\n");
    fprintf(constants, "    'ZEND_POST_INC_OBJ' => 134,\n");
    fprintf(constants, "    'ZEND_POST_DEC_OBJ' => 135,\n");
    fprintf(constants, "    'ZEND_ECHO' => 136,\n");
    fprintf(constants, "    'ZEND_OP_DATA' => 137,\n");
    fprintf(constants, "    'ZEND_INSTANCEOF' => 138,\n");
    fprintf(constants, "    'ZEND_GENERATOR_CREATE' => 139,\n");
    fprintf(constants, "    'ZEND_MAKE_REF' => 140,\n");
    fprintf(constants, "    'ZEND_DECLARE_FUNCTION' => 141,\n");
    fprintf(constants, "    'ZEND_DECLARE_LAMBDA_FUNCTION' => 142,\n");
    fprintf(constants, "    'ZEND_DECLARE_CONST' => 143,\n");
    fprintf(constants, "    'ZEND_DECLARE_CLASS' => 144,\n");
    fprintf(constants, "    'ZEND_DECLARE_CLASS_DELAYED' => 145,\n");
    fprintf(constants, "    'ZEND_DECLARE_ANON_CLASS' => 146,\n");
    fprintf(constants, "    'ZEND_ADD_ARRAY_UNPACK' => 147,\n");
    fprintf(constants, "    'ZEND_ISSET_ISEMPTY_PROP_OBJ' => 148,\n");
    fprintf(constants, "    'ZEND_HANDLE_EXCEPTION' => 149,\n");
    fprintf(constants, "    'ZEND_USER_OPCODE' => 150,\n");
    fprintf(constants, "    'ZEND_ASSERT_CHECK' => 151,\n");
    fprintf(constants, "    'ZEND_JMP_SET' => 152,\n");
    fprintf(constants, "    'ZEND_UNSET_CV' => 153,\n");
    fprintf(constants, "    'ZEND_ISSET_ISEMPTY_CV' => 154,\n");
    fprintf(constants, "    'ZEND_FETCH_LIST_W' => 155,\n");
    fprintf(constants, "    'ZEND_SEPARATE' => 156,\n");
    fprintf(constants, "    'ZEND_FETCH_CLASS_NAME' => 157,\n");
    fprintf(constants, "    'ZEND_CALL_TRAMPOLINE' => 158,\n");
    fprintf(constants, "    'ZEND_DISCARD_EXCEPTION' => 159,\n");
    fprintf(constants, "    'ZEND_YIELD' => 160,\n");
    fprintf(constants, "    'ZEND_GENERATOR_RETURN' => 161,\n");
    fprintf(constants, "    'ZEND_FAST_CALL' => 162,\n");
    fprintf(constants, "    'ZEND_FAST_RET' => 163,\n");
    fprintf(constants, "    'ZEND_RECV_VARIADIC' => 164,\n");
    fprintf(constants, "    'ZEND_SEND_UNPACK' => 165,\n");
    fprintf(constants, "    'ZEND_YIELD_FROM' => 166,\n");
    fprintf(constants, "    'ZEND_COPY_TMP' => 167,\n");
    fprintf(constants, "    'ZEND_BIND_GLOBAL' => 168,\n");
    fprintf(constants, "    'ZEND_COALESCE' => 169,\n");
    fprintf(constants, "    'ZEND_SPACESHIP' => 170,\n");
    fprintf(constants, "    'ZEND_FUNC_NUM_ARGS' => 171,\n");
    fprintf(constants, "    'ZEND_FUNC_GET_ARGS' => 172,\n");
    fprintf(constants, "    'ZEND_FETCH_STATIC_PROP_R' => 173,\n");
    fprintf(constants, "    'ZEND_FETCH_STATIC_PROP_W' => 174,\n");
    fprintf(constants, "    'ZEND_FETCH_STATIC_PROP_RW' => 175,\n");
    fprintf(constants, "    'ZEND_FETCH_STATIC_PROP_IS' => 176,\n");
    fprintf(constants, "    'ZEND_FETCH_STATIC_PROP_FUNC_ARG' => 177,\n");
    fprintf(constants, "    'ZEND_FETCH_STATIC_PROP_UNSET' => 178,\n");
    fprintf(constants, "    'ZEND_UNSET_STATIC_PROP' => 179,\n");
    fprintf(constants, "    'ZEND_ISSET_ISEMPTY_STATIC_PROP' => 180,\n");
    fprintf(constants, "    'ZEND_FETCH_CLASS_CONSTANT' => 181,\n");
    fprintf(constants, "    'ZEND_BIND_LEXICAL' => 182,\n");
    fprintf(constants, "    'ZEND_BIND_STATIC' => 183,\n");
    fprintf(constants, "    'ZEND_FETCH_THIS' => 184,\n");
    fprintf(constants, "    'ZEND_SEND_FUNC_ARG' => 185,\n");
    fprintf(constants, "    'ZEND_ISSET_ISEMPTY_THIS' => 186,\n");
    fprintf(constants, "    'ZEND_SWITCH_LONG' => 187,\n");
    fprintf(constants, "    'ZEND_SWITCH_STRING' => 188,\n");
    fprintf(constants, "    'ZEND_IN_ARRAY' => 189,\n");
    fprintf(constants, "    'ZEND_COUNT' => 190,\n");
    fprintf(constants, "    'ZEND_GET_CLASS' => 191,\n");
    fprintf(constants, "    'ZEND_GET_CALLED_CLASS' => 192,\n");
    fprintf(constants, "    'ZEND_GET_TYPE' => 193,\n");
    fprintf(constants, "    'ZEND_ARRAY_KEY_EXISTS' => 194,\n");
    fprintf(constants, "    'ZEND_MATCH' => 195,\n");
    fprintf(constants, "    'ZEND_CASE_STRICT' => 196,\n");
    fprintf(constants, "    'ZEND_MATCH_ERROR' => 197,\n");
    fprintf(constants, "    'ZEND_JMP_NULL' => 198,\n");
    fprintf(constants, "    'ZEND_CHECK_UNDEF_ARGS' => 199,\n");
    fprintf(constants, "    'ZEND_FETCH_GLOBALS' => 200,\n");
    fprintf(constants, "    'ZEND_VERIFY_NEVER_TYPE' => 201,\n");
    fprintf(constants, "    'ZEND_CALLABLE_CONVERT' => 202,\n");
    fprintf(constants, "    'ZEND_BIND_INIT_STATIC_OR_JMP' => 203,\n");
    fprintf(constants, "    'ZEND_FRAMELESS_ICALL_0' => 204,\n");
    fprintf(constants, "    'ZEND_FRAMELESS_ICALL_1' => 205,\n");
    fprintf(constants, "    'ZEND_FRAMELESS_ICALL_2' => 206,\n");
    fprintf(constants, "    'ZEND_FRAMELESS_ICALL_3' => 207,\n");
    fprintf(constants, "    'ZEND_JMP_FRAMELESS' => 208,\n");
    fprintf(constants, "    'ZEND_INIT_PARENT_PROPERTY_HOOK_CALL' => 209,\n");
    fprintf(constants, "    'ZEND_VM_LAST_OPCODE' => 209,\n");
    fputs("];\n", constants);
    fclose(constants);

    fputs("{\n", layouts);
    fprintf(layouts, "    \"meta\": {\"php\": \"%d.%d\", \"api\": %d, \"zts\": %d, \"debug\": %d},\n", PHP_MAJOR_VERSION, PHP_MINOR_VERSION, ZEND_MODULE_API_NO, (int)USING_ZTS, (int)ZEND_DEBUG);
    fputs("    \"structs\": {\n", layouts);
    fputs("        \"zval\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zval));
    fprintf(layouts, "\"value\": %zu", offsetof(zval, value));
    fprintf(layouts, ", \"u1\": %zu", offsetof(zval, u1));
    fprintf(layouts, ", \"u2\": %zu", offsetof(zval, u2));
    fputs("}},\n", layouts);
    fputs("        \"zend_refcounted\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_refcounted));
    fprintf(layouts, "\"gc\": %zu", offsetof(zend_refcounted, gc));
    fputs("}},\n", layouts);
    fputs("        \"zend_string\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_string));
    fprintf(layouts, "\"gc\": %zu", offsetof(zend_string, gc));
    fprintf(layouts, ", \"h\": %zu", offsetof(zend_string, h));
    fprintf(layouts, ", \"len\": %zu", offsetof(zend_string, len));
    fprintf(layouts, ", \"val\": %zu", offsetof(zend_string, val));
    fputs("}},\n", layouts);
    fputs("        \"zend_array\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_array));
    fprintf(layouts, "\"gc\": %zu", offsetof(zend_array, gc));
    fprintf(layouts, ", \"u\": %zu", offsetof(zend_array, u));
    fprintf(layouts, ", \"nTableMask\": %zu", offsetof(zend_array, nTableMask));
    fprintf(layouts, ", \"arHash\": %zu", offsetof(zend_array, arHash));
    fprintf(layouts, ", \"arData\": %zu", offsetof(zend_array, arData));
    fprintf(layouts, ", \"arPacked\": %zu", offsetof(zend_array, arPacked));
    fprintf(layouts, ", \"nNumUsed\": %zu", offsetof(zend_array, nNumUsed));
    fprintf(layouts, ", \"nNumOfElements\": %zu", offsetof(zend_array, nNumOfElements));
    fprintf(layouts, ", \"nTableSize\": %zu", offsetof(zend_array, nTableSize));
    fprintf(layouts, ", \"nInternalPointer\": %zu", offsetof(zend_array, nInternalPointer));
    fprintf(layouts, ", \"nNextFreeElement\": %zu", offsetof(zend_array, nNextFreeElement));
    fprintf(layouts, ", \"pDestructor\": %zu", offsetof(zend_array, pDestructor));
    fputs("}},\n", layouts);
    fputs("        \"Bucket\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(Bucket));
    fprintf(layouts, "\"val\": %zu", offsetof(Bucket, val));
    fprintf(layouts, ", \"h\": %zu", offsetof(Bucket, h));
    fprintf(layouts, ", \"key\": %zu", offsetof(Bucket, key));
    fputs("}},\n", layouts);
    fputs("        \"zend_object\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_object));
    fprintf(layouts, "\"gc\": %zu", offsetof(zend_object, gc));
    fprintf(layouts, ", \"handle\": %zu", offsetof(zend_object, handle));
    fprintf(layouts, ", \"extra_flags\": %zu", offsetof(zend_object, extra_flags));
    fprintf(layouts, ", \"ce\": %zu", offsetof(zend_object, ce));
    fprintf(layouts, ", \"handlers\": %zu", offsetof(zend_object, handlers));
    fprintf(layouts, ", \"properties\": %zu", offsetof(zend_object, properties));
    fprintf(layouts, ", \"properties_table\": %zu", offsetof(zend_object, properties_table));
    fputs("}},\n", layouts);
    fputs("        \"zend_resource\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_resource));
    fprintf(layouts, "\"gc\": %zu", offsetof(zend_resource, gc));
    fprintf(layouts, ", \"handle\": %zu", offsetof(zend_resource, handle));
    fprintf(layouts, ", \"type\": %zu", offsetof(zend_resource, type));
    fprintf(layouts, ", \"ptr\": %zu", offsetof(zend_resource, ptr));
    fputs("}},\n", layouts);
    fputs("        \"zend_reference\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_reference));
    fprintf(layouts, "\"gc\": %zu", offsetof(zend_reference, gc));
    fprintf(layouts, ", \"val\": %zu", offsetof(zend_reference, val));
    fprintf(layouts, ", \"sources\": %zu", offsetof(zend_reference, sources));
    fputs("}},\n", layouts);
    fputs("        \"zend_class_entry\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_class_entry));
    fprintf(layouts, "\"type\": %zu", offsetof(zend_class_entry, type));
    fprintf(layouts, ", \"name\": %zu", offsetof(zend_class_entry, name));
    fprintf(layouts, ", \"parent\": %zu", offsetof(zend_class_entry, parent));
    fprintf(layouts, ", \"parent_name\": %zu", offsetof(zend_class_entry, parent_name));
    fprintf(layouts, ", \"refcount\": %zu", offsetof(zend_class_entry, refcount));
    fprintf(layouts, ", \"ce_flags\": %zu", offsetof(zend_class_entry, ce_flags));
    fprintf(layouts, ", \"default_properties_count\": %zu", offsetof(zend_class_entry, default_properties_count));
    fprintf(layouts, ", \"default_static_members_count\": %zu", offsetof(zend_class_entry, default_static_members_count));
    fprintf(layouts, ", \"default_properties_table\": %zu", offsetof(zend_class_entry, default_properties_table));
    fprintf(layouts, ", \"default_static_members_table\": %zu", offsetof(zend_class_entry, default_static_members_table));
    fprintf(layouts, ", \"static_members_table__ptr\": %zu", offsetof(zend_class_entry, static_members_table__ptr));
    fprintf(layouts, ", \"function_table\": %zu", offsetof(zend_class_entry, function_table));
    fprintf(layouts, ", \"properties_info\": %zu", offsetof(zend_class_entry, properties_info));
    fprintf(layouts, ", \"constants_table\": %zu", offsetof(zend_class_entry, constants_table));
    fprintf(layouts, ", \"mutable_data__ptr\": %zu", offsetof(zend_class_entry, mutable_data__ptr));
    fprintf(layouts, ", \"inheritance_cache\": %zu", offsetof(zend_class_entry, inheritance_cache));
    fprintf(layouts, ", \"properties_info_table\": %zu", offsetof(zend_class_entry, properties_info_table));
    fprintf(layouts, ", \"constructor\": %zu", offsetof(zend_class_entry, constructor));
    fprintf(layouts, ", \"destructor\": %zu", offsetof(zend_class_entry, destructor));
    fprintf(layouts, ", \"clone\": %zu", offsetof(zend_class_entry, clone));
    fprintf(layouts, ", \"__get\": %zu", offsetof(zend_class_entry, __get));
    fprintf(layouts, ", \"__set\": %zu", offsetof(zend_class_entry, __set));
    fprintf(layouts, ", \"__unset\": %zu", offsetof(zend_class_entry, __unset));
    fprintf(layouts, ", \"__isset\": %zu", offsetof(zend_class_entry, __isset));
    fprintf(layouts, ", \"__call\": %zu", offsetof(zend_class_entry, __call));
    fprintf(layouts, ", \"__callstatic\": %zu", offsetof(zend_class_entry, __callstatic));
    fprintf(layouts, ", \"__tostring\": %zu", offsetof(zend_class_entry, __tostring));
    fprintf(layouts, ", \"__debugInfo\": %zu", offsetof(zend_class_entry, __debugInfo));
    fprintf(layouts, ", \"__serialize\": %zu", offsetof(zend_class_entry, __serialize));
    fprintf(layouts, ", \"__unserialize\": %zu", offsetof(zend_class_entry, __unserialize));
    fprintf(layouts, ", \"default_object_handlers\": %zu", offsetof(zend_class_entry, default_object_handlers));
    fprintf(layouts, ", \"iterator_funcs_ptr\": %zu", offsetof(zend_class_entry, iterator_funcs_ptr));
    fprintf(layouts, ", \"arrayaccess_funcs_ptr\": %zu", offsetof(zend_class_entry, arrayaccess_funcs_ptr));
    fprintf(layouts, ", \"create_object\": %zu", offsetof(zend_class_entry, create_object));
    fprintf(layouts, ", \"interface_gets_implemented\": %zu", offsetof(zend_class_entry, interface_gets_implemented));
    fprintf(layouts, ", \"get_iterator\": %zu", offsetof(zend_class_entry, get_iterator));
    fprintf(layouts, ", \"get_static_method\": %zu", offsetof(zend_class_entry, get_static_method));
    fprintf(layouts, ", \"serialize\": %zu", offsetof(zend_class_entry, serialize));
    fprintf(layouts, ", \"unserialize\": %zu", offsetof(zend_class_entry, unserialize));
    fprintf(layouts, ", \"num_interfaces\": %zu", offsetof(zend_class_entry, num_interfaces));
    fprintf(layouts, ", \"num_traits\": %zu", offsetof(zend_class_entry, num_traits));
    fprintf(layouts, ", \"num_hooked_props\": %zu", offsetof(zend_class_entry, num_hooked_props));
    fprintf(layouts, ", \"num_hooked_prop_variance_checks\": %zu", offsetof(zend_class_entry, num_hooked_prop_variance_checks));
    fprintf(layouts, ", \"interfaces\": %zu", offsetof(zend_class_entry, interfaces));
    fprintf(layouts, ", \"interface_names\": %zu", offsetof(zend_class_entry, interface_names));
    fprintf(layouts, ", \"trait_names\": %zu", offsetof(zend_class_entry, trait_names));
    fprintf(layouts, ", \"trait_aliases\": %zu", offsetof(zend_class_entry, trait_aliases));
    fprintf(layouts, ", \"trait_precedences\": %zu", offsetof(zend_class_entry, trait_precedences));
    fprintf(layouts, ", \"attributes\": %zu", offsetof(zend_class_entry, attributes));
    fprintf(layouts, ", \"enum_backing_type\": %zu", offsetof(zend_class_entry, enum_backing_type));
    fprintf(layouts, ", \"backed_enum_table\": %zu", offsetof(zend_class_entry, backed_enum_table));
    fprintf(layouts, ", \"doc_comment\": %zu", offsetof(zend_class_entry, doc_comment));
    fprintf(layouts, ", \"info\": %zu", offsetof(zend_class_entry, info));
    fputs("}},\n", layouts);
    fputs("        \"zend_class_constant\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_class_constant));
    fprintf(layouts, "\"value\": %zu", offsetof(zend_class_constant, value));
    fprintf(layouts, ", \"doc_comment\": %zu", offsetof(zend_class_constant, doc_comment));
    fprintf(layouts, ", \"attributes\": %zu", offsetof(zend_class_constant, attributes));
    fprintf(layouts, ", \"ce\": %zu", offsetof(zend_class_constant, ce));
    fprintf(layouts, ", \"type\": %zu", offsetof(zend_class_constant, type));
    fputs("}},\n", layouts);
    fputs("        \"zend_class_name\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_class_name));
    fprintf(layouts, "\"name\": %zu", offsetof(zend_class_name, name));
    fprintf(layouts, ", \"lc_name\": %zu", offsetof(zend_class_name, lc_name));
    fputs("}},\n", layouts);
    fputs("        \"zend_property_info\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_property_info));
    fprintf(layouts, "\"offset\": %zu", offsetof(zend_property_info, offset));
    fprintf(layouts, ", \"flags\": %zu", offsetof(zend_property_info, flags));
    fprintf(layouts, ", \"name\": %zu", offsetof(zend_property_info, name));
    fprintf(layouts, ", \"doc_comment\": %zu", offsetof(zend_property_info, doc_comment));
    fprintf(layouts, ", \"attributes\": %zu", offsetof(zend_property_info, attributes));
    fprintf(layouts, ", \"ce\": %zu", offsetof(zend_property_info, ce));
    fprintf(layouts, ", \"type\": %zu", offsetof(zend_property_info, type));
    fprintf(layouts, ", \"prototype\": %zu", offsetof(zend_property_info, prototype));
    fprintf(layouts, ", \"hooks\": %zu", offsetof(zend_property_info, hooks));
    fputs("}},\n", layouts);
    fputs("        \"zend_type_list\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_type_list));
    fprintf(layouts, "\"num_types\": %zu", offsetof(zend_type_list, num_types));
    fprintf(layouts, ", \"types\": %zu", offsetof(zend_type_list, types));
    fputs("}},\n", layouts);
    fputs("        \"zend_constant\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_constant));
    fprintf(layouts, "\"value\": %zu", offsetof(zend_constant, value));
    fprintf(layouts, ", \"name\": %zu", offsetof(zend_constant, name));
    fputs("}},\n", layouts);
    fputs("        \"zend_attribute\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_attribute));
    fprintf(layouts, "\"name\": %zu", offsetof(zend_attribute, name));
    fprintf(layouts, ", \"lcname\": %zu", offsetof(zend_attribute, lcname));
    fprintf(layouts, ", \"flags\": %zu", offsetof(zend_attribute, flags));
    fprintf(layouts, ", \"lineno\": %zu", offsetof(zend_attribute, lineno));
    fprintf(layouts, ", \"offset\": %zu", offsetof(zend_attribute, offset));
    fprintf(layouts, ", \"argc\": %zu", offsetof(zend_attribute, argc));
    fprintf(layouts, ", \"args\": %zu", offsetof(zend_attribute, args));
    fputs("}},\n", layouts);
    fputs("        \"zend_attribute_arg\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_attribute_arg));
    fprintf(layouts, "\"name\": %zu", offsetof(zend_attribute_arg, name));
    fprintf(layouts, ", \"value\": %zu", offsetof(zend_attribute_arg, value));
    fputs("}},\n", layouts);
    fputs("        \"zend_op_array\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_op_array));
    fprintf(layouts, "\"type\": %zu", offsetof(zend_op_array, type));
    fprintf(layouts, ", \"arg_flags\": %zu", offsetof(zend_op_array, arg_flags));
    fprintf(layouts, ", \"fn_flags\": %zu", offsetof(zend_op_array, fn_flags));
    fprintf(layouts, ", \"function_name\": %zu", offsetof(zend_op_array, function_name));
    fprintf(layouts, ", \"scope\": %zu", offsetof(zend_op_array, scope));
    fprintf(layouts, ", \"prototype\": %zu", offsetof(zend_op_array, prototype));
    fprintf(layouts, ", \"num_args\": %zu", offsetof(zend_op_array, num_args));
    fprintf(layouts, ", \"required_num_args\": %zu", offsetof(zend_op_array, required_num_args));
    fprintf(layouts, ", \"arg_info\": %zu", offsetof(zend_op_array, arg_info));
    fprintf(layouts, ", \"attributes\": %zu", offsetof(zend_op_array, attributes));
    fprintf(layouts, ", \"run_time_cache__ptr\": %zu", offsetof(zend_op_array, run_time_cache__ptr));
    fprintf(layouts, ", \"doc_comment\": %zu", offsetof(zend_op_array, doc_comment));
    fprintf(layouts, ", \"T\": %zu", offsetof(zend_op_array, T));
    fprintf(layouts, ", \"prop_info\": %zu", offsetof(zend_op_array, prop_info));
    fprintf(layouts, ", \"cache_size\": %zu", offsetof(zend_op_array, cache_size));
    fprintf(layouts, ", \"last_var\": %zu", offsetof(zend_op_array, last_var));
    fprintf(layouts, ", \"last\": %zu", offsetof(zend_op_array, last));
    fprintf(layouts, ", \"opcodes\": %zu", offsetof(zend_op_array, opcodes));
    fprintf(layouts, ", \"static_variables_ptr__ptr\": %zu", offsetof(zend_op_array, static_variables_ptr__ptr));
    fprintf(layouts, ", \"static_variables\": %zu", offsetof(zend_op_array, static_variables));
    fprintf(layouts, ", \"vars\": %zu", offsetof(zend_op_array, vars));
    fprintf(layouts, ", \"refcount\": %zu", offsetof(zend_op_array, refcount));
    fprintf(layouts, ", \"last_live_range\": %zu", offsetof(zend_op_array, last_live_range));
    fprintf(layouts, ", \"last_try_catch\": %zu", offsetof(zend_op_array, last_try_catch));
    fprintf(layouts, ", \"live_range\": %zu", offsetof(zend_op_array, live_range));
    fprintf(layouts, ", \"try_catch_array\": %zu", offsetof(zend_op_array, try_catch_array));
    fprintf(layouts, ", \"filename\": %zu", offsetof(zend_op_array, filename));
    fprintf(layouts, ", \"line_start\": %zu", offsetof(zend_op_array, line_start));
    fprintf(layouts, ", \"line_end\": %zu", offsetof(zend_op_array, line_end));
    fprintf(layouts, ", \"last_literal\": %zu", offsetof(zend_op_array, last_literal));
    fprintf(layouts, ", \"num_dynamic_func_defs\": %zu", offsetof(zend_op_array, num_dynamic_func_defs));
    fprintf(layouts, ", \"literals\": %zu", offsetof(zend_op_array, literals));
    fprintf(layouts, ", \"dynamic_func_defs\": %zu", offsetof(zend_op_array, dynamic_func_defs));
    fprintf(layouts, ", \"reserved\": %zu", offsetof(zend_op_array, reserved));
    fputs("}},\n", layouts);
    fputs("        \"zend_internal_function\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_internal_function));
    fprintf(layouts, "\"type\": %zu", offsetof(zend_internal_function, type));
    fprintf(layouts, ", \"arg_flags\": %zu", offsetof(zend_internal_function, arg_flags));
    fprintf(layouts, ", \"fn_flags\": %zu", offsetof(zend_internal_function, fn_flags));
    fprintf(layouts, ", \"function_name\": %zu", offsetof(zend_internal_function, function_name));
    fprintf(layouts, ", \"scope\": %zu", offsetof(zend_internal_function, scope));
    fprintf(layouts, ", \"prototype\": %zu", offsetof(zend_internal_function, prototype));
    fprintf(layouts, ", \"num_args\": %zu", offsetof(zend_internal_function, num_args));
    fprintf(layouts, ", \"required_num_args\": %zu", offsetof(zend_internal_function, required_num_args));
    fprintf(layouts, ", \"arg_info\": %zu", offsetof(zend_internal_function, arg_info));
    fprintf(layouts, ", \"attributes\": %zu", offsetof(zend_internal_function, attributes));
    fprintf(layouts, ", \"run_time_cache__ptr\": %zu", offsetof(zend_internal_function, run_time_cache__ptr));
    fprintf(layouts, ", \"doc_comment\": %zu", offsetof(zend_internal_function, doc_comment));
    fprintf(layouts, ", \"T\": %zu", offsetof(zend_internal_function, T));
    fprintf(layouts, ", \"prop_info\": %zu", offsetof(zend_internal_function, prop_info));
    fprintf(layouts, ", \"handler\": %zu", offsetof(zend_internal_function, handler));
    fprintf(layouts, ", \"module\": %zu", offsetof(zend_internal_function, module));
    fprintf(layouts, ", \"frameless_function_infos\": %zu", offsetof(zend_internal_function, frameless_function_infos));
    fprintf(layouts, ", \"reserved\": %zu", offsetof(zend_internal_function, reserved));
    fputs("}},\n", layouts);
    fputs("        \"zend_op\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_op));
    fprintf(layouts, "\"handler\": %zu", offsetof(zend_op, handler));
    fprintf(layouts, ", \"op1\": %zu", offsetof(zend_op, op1));
    fprintf(layouts, ", \"op2\": %zu", offsetof(zend_op, op2));
    fprintf(layouts, ", \"result\": %zu", offsetof(zend_op, result));
    fprintf(layouts, ", \"extended_value\": %zu", offsetof(zend_op, extended_value));
    fprintf(layouts, ", \"lineno\": %zu", offsetof(zend_op, lineno));
    fprintf(layouts, ", \"opcode\": %zu", offsetof(zend_op, opcode));
    fprintf(layouts, ", \"op1_type\": %zu", offsetof(zend_op, op1_type));
    fprintf(layouts, ", \"op2_type\": %zu", offsetof(zend_op, op2_type));
    fprintf(layouts, ", \"result_type\": %zu", offsetof(zend_op, result_type));
    fputs("}},\n", layouts);
    fputs("        \"zend_execute_data\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_execute_data));
    fprintf(layouts, "\"opline\": %zu", offsetof(zend_execute_data, opline));
    fprintf(layouts, ", \"call\": %zu", offsetof(zend_execute_data, call));
    fprintf(layouts, ", \"return_value\": %zu", offsetof(zend_execute_data, return_value));
    fprintf(layouts, ", \"func\": %zu", offsetof(zend_execute_data, func));
    fprintf(layouts, ", \"This\": %zu", offsetof(zend_execute_data, This));
    fprintf(layouts, ", \"prev_execute_data\": %zu", offsetof(zend_execute_data, prev_execute_data));
    fprintf(layouts, ", \"symbol_table\": %zu", offsetof(zend_execute_data, symbol_table));
    fprintf(layouts, ", \"run_time_cache\": %zu", offsetof(zend_execute_data, run_time_cache));
    fprintf(layouts, ", \"extra_named_params\": %zu", offsetof(zend_execute_data, extra_named_params));
    fputs("}},\n", layouts);
    fputs("        \"zend_objects_store\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_objects_store));
    fprintf(layouts, "\"object_buckets\": %zu", offsetof(zend_objects_store, object_buckets));
    fprintf(layouts, ", \"top\": %zu", offsetof(zend_objects_store, top));
    fprintf(layouts, ", \"size\": %zu", offsetof(zend_objects_store, size));
    fprintf(layouts, ", \"free_list_head\": %zu", offsetof(zend_objects_store, free_list_head));
    fputs("}},\n", layouts);
    fputs("        \"zend_executor_globals\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_executor_globals));
    fprintf(layouts, "\"uninitialized_zval\": %zu", offsetof(zend_executor_globals, uninitialized_zval));
    fprintf(layouts, ", \"error_zval\": %zu", offsetof(zend_executor_globals, error_zval));
    fprintf(layouts, ", \"symtable_cache\": %zu", offsetof(zend_executor_globals, symtable_cache));
    fprintf(layouts, ", \"symtable_cache_limit\": %zu", offsetof(zend_executor_globals, symtable_cache_limit));
    fprintf(layouts, ", \"symtable_cache_ptr\": %zu", offsetof(zend_executor_globals, symtable_cache_ptr));
    fprintf(layouts, ", \"symbol_table\": %zu", offsetof(zend_executor_globals, symbol_table));
    fprintf(layouts, ", \"included_files\": %zu", offsetof(zend_executor_globals, included_files));
    fprintf(layouts, ", \"bailout\": %zu", offsetof(zend_executor_globals, bailout));
    fprintf(layouts, ", \"error_reporting\": %zu", offsetof(zend_executor_globals, error_reporting));
    fprintf(layouts, ", \"exit_status\": %zu", offsetof(zend_executor_globals, exit_status));
    fprintf(layouts, ", \"function_table\": %zu", offsetof(zend_executor_globals, function_table));
    fprintf(layouts, ", \"class_table\": %zu", offsetof(zend_executor_globals, class_table));
    fprintf(layouts, ", \"zend_constants\": %zu", offsetof(zend_executor_globals, zend_constants));
    fprintf(layouts, ", \"vm_stack_top\": %zu", offsetof(zend_executor_globals, vm_stack_top));
    fprintf(layouts, ", \"vm_stack_end\": %zu", offsetof(zend_executor_globals, vm_stack_end));
    fprintf(layouts, ", \"vm_stack\": %zu", offsetof(zend_executor_globals, vm_stack));
    fprintf(layouts, ", \"vm_stack_page_size\": %zu", offsetof(zend_executor_globals, vm_stack_page_size));
    fprintf(layouts, ", \"current_execute_data\": %zu", offsetof(zend_executor_globals, current_execute_data));
    fprintf(layouts, ", \"fake_scope\": %zu", offsetof(zend_executor_globals, fake_scope));
    fprintf(layouts, ", \"jit_trace_num\": %zu", offsetof(zend_executor_globals, jit_trace_num));
    fprintf(layouts, ", \"current_observed_frame\": %zu", offsetof(zend_executor_globals, current_observed_frame));
    fprintf(layouts, ", \"ticks_count\": %zu", offsetof(zend_executor_globals, ticks_count));
    fprintf(layouts, ", \"precision\": %zu", offsetof(zend_executor_globals, precision));
    fprintf(layouts, ", \"persistent_constants_count\": %zu", offsetof(zend_executor_globals, persistent_constants_count));
    fprintf(layouts, ", \"persistent_functions_count\": %zu", offsetof(zend_executor_globals, persistent_functions_count));
    fprintf(layouts, ", \"persistent_classes_count\": %zu", offsetof(zend_executor_globals, persistent_classes_count));
    fprintf(layouts, ", \"no_extensions\": %zu", offsetof(zend_executor_globals, no_extensions));
    fprintf(layouts, ", \"full_tables_cleanup\": %zu", offsetof(zend_executor_globals, full_tables_cleanup));
    fprintf(layouts, ", \"vm_interrupt\": %zu", offsetof(zend_executor_globals, vm_interrupt));
    fprintf(layouts, ", \"timed_out\": %zu", offsetof(zend_executor_globals, timed_out));
    fprintf(layouts, ", \"in_autoload\": %zu", offsetof(zend_executor_globals, in_autoload));
    fprintf(layouts, ", \"hard_timeout\": %zu", offsetof(zend_executor_globals, hard_timeout));
    fprintf(layouts, ", \"stack_base\": %zu", offsetof(zend_executor_globals, stack_base));
    fprintf(layouts, ", \"stack_limit\": %zu", offsetof(zend_executor_globals, stack_limit));
    fprintf(layouts, ", \"regular_list\": %zu", offsetof(zend_executor_globals, regular_list));
    fprintf(layouts, ", \"persistent_list\": %zu", offsetof(zend_executor_globals, persistent_list));
    fprintf(layouts, ", \"user_error_handler_error_reporting\": %zu", offsetof(zend_executor_globals, user_error_handler_error_reporting));
    fprintf(layouts, ", \"exception_ignore_args\": %zu", offsetof(zend_executor_globals, exception_ignore_args));
    fprintf(layouts, ", \"user_error_handler\": %zu", offsetof(zend_executor_globals, user_error_handler));
    fprintf(layouts, ", \"user_exception_handler\": %zu", offsetof(zend_executor_globals, user_exception_handler));
    fprintf(layouts, ", \"user_error_handlers_error_reporting\": %zu", offsetof(zend_executor_globals, user_error_handlers_error_reporting));
    fprintf(layouts, ", \"user_error_handlers\": %zu", offsetof(zend_executor_globals, user_error_handlers));
    fprintf(layouts, ", \"user_exception_handlers\": %zu", offsetof(zend_executor_globals, user_exception_handlers));
    fprintf(layouts, ", \"exception_class\": %zu", offsetof(zend_executor_globals, exception_class));
    fprintf(layouts, ", \"error_handling\": %zu", offsetof(zend_executor_globals, error_handling));
    fprintf(layouts, ", \"capture_warnings_during_sccp\": %zu", offsetof(zend_executor_globals, capture_warnings_during_sccp));
    fprintf(layouts, ", \"timeout_seconds\": %zu", offsetof(zend_executor_globals, timeout_seconds));
    fprintf(layouts, ", \"ini_directives\": %zu", offsetof(zend_executor_globals, ini_directives));
    fprintf(layouts, ", \"modified_ini_directives\": %zu", offsetof(zend_executor_globals, modified_ini_directives));
    fprintf(layouts, ", \"error_reporting_ini_entry\": %zu", offsetof(zend_executor_globals, error_reporting_ini_entry));
    fprintf(layouts, ", \"objects_store\": %zu", offsetof(zend_executor_globals, objects_store));
    fprintf(layouts, ", \"lazy_objects_store\": %zu", offsetof(zend_executor_globals, lazy_objects_store));
    fprintf(layouts, ", \"exception\": %zu", offsetof(zend_executor_globals, exception));
    fprintf(layouts, ", \"prev_exception\": %zu", offsetof(zend_executor_globals, prev_exception));
    fprintf(layouts, ", \"opline_before_exception\": %zu", offsetof(zend_executor_globals, opline_before_exception));
    fprintf(layouts, ", \"exception_op\": %zu", offsetof(zend_executor_globals, exception_op));
    fprintf(layouts, ", \"current_module\": %zu", offsetof(zend_executor_globals, current_module));
    fprintf(layouts, ", \"active\": %zu", offsetof(zend_executor_globals, active));
    fprintf(layouts, ", \"flags\": %zu", offsetof(zend_executor_globals, flags));
    fprintf(layouts, ", \"assertions\": %zu", offsetof(zend_executor_globals, assertions));
    fprintf(layouts, ", \"ht_iterators_count\": %zu", offsetof(zend_executor_globals, ht_iterators_count));
    fprintf(layouts, ", \"ht_iterators_used\": %zu", offsetof(zend_executor_globals, ht_iterators_used));
    fprintf(layouts, ", \"ht_iterators\": %zu", offsetof(zend_executor_globals, ht_iterators));
    fprintf(layouts, ", \"ht_iterators_slots\": %zu", offsetof(zend_executor_globals, ht_iterators_slots));
    fprintf(layouts, ", \"saved_fpu_cw_ptr\": %zu", offsetof(zend_executor_globals, saved_fpu_cw_ptr));
    fprintf(layouts, ", \"trampoline\": %zu", offsetof(zend_executor_globals, trampoline));
    fprintf(layouts, ", \"call_trampoline_op\": %zu", offsetof(zend_executor_globals, call_trampoline_op));
    fprintf(layouts, ", \"weakrefs\": %zu", offsetof(zend_executor_globals, weakrefs));
    fprintf(layouts, ", \"exception_string_param_max_len\": %zu", offsetof(zend_executor_globals, exception_string_param_max_len));
    fprintf(layouts, ", \"get_gc_buffer\": %zu", offsetof(zend_executor_globals, get_gc_buffer));
    fprintf(layouts, ", \"main_fiber_context\": %zu", offsetof(zend_executor_globals, main_fiber_context));
    fprintf(layouts, ", \"current_fiber_context\": %zu", offsetof(zend_executor_globals, current_fiber_context));
    fprintf(layouts, ", \"active_fiber\": %zu", offsetof(zend_executor_globals, active_fiber));
    fprintf(layouts, ", \"fiber_stack_size\": %zu", offsetof(zend_executor_globals, fiber_stack_size));
    fprintf(layouts, ", \"record_errors\": %zu", offsetof(zend_executor_globals, record_errors));
    fprintf(layouts, ", \"num_errors\": %zu", offsetof(zend_executor_globals, num_errors));
    fprintf(layouts, ", \"errors\": %zu", offsetof(zend_executor_globals, errors));
    fprintf(layouts, ", \"filename_override\": %zu", offsetof(zend_executor_globals, filename_override));
    fprintf(layouts, ", \"lineno_override\": %zu", offsetof(zend_executor_globals, lineno_override));
    fprintf(layouts, ", \"call_stack\": %zu", offsetof(zend_executor_globals, call_stack));
    fprintf(layouts, ", \"max_allowed_stack_size\": %zu", offsetof(zend_executor_globals, max_allowed_stack_size));
    fprintf(layouts, ", \"reserved_stack_size\": %zu", offsetof(zend_executor_globals, reserved_stack_size));
    fprintf(layouts, ", \"strtod_state\": %zu", offsetof(zend_executor_globals, strtod_state));
    fprintf(layouts, ", \"reserved\": %zu", offsetof(zend_executor_globals, reserved));
    fputs("}},\n", layouts);
    fputs("        \"zend_compiler_globals\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_compiler_globals));
    fprintf(layouts, "\"loop_var_stack\": %zu", offsetof(zend_compiler_globals, loop_var_stack));
    fprintf(layouts, ", \"active_class_entry\": %zu", offsetof(zend_compiler_globals, active_class_entry));
    fprintf(layouts, ", \"compiled_filename\": %zu", offsetof(zend_compiler_globals, compiled_filename));
    fprintf(layouts, ", \"zend_lineno\": %zu", offsetof(zend_compiler_globals, zend_lineno));
    fprintf(layouts, ", \"active_op_array\": %zu", offsetof(zend_compiler_globals, active_op_array));
    fprintf(layouts, ", \"function_table\": %zu", offsetof(zend_compiler_globals, function_table));
    fprintf(layouts, ", \"class_table\": %zu", offsetof(zend_compiler_globals, class_table));
    fprintf(layouts, ", \"auto_globals\": %zu", offsetof(zend_compiler_globals, auto_globals));
    fprintf(layouts, ", \"parse_error\": %zu", offsetof(zend_compiler_globals, parse_error));
    fprintf(layouts, ", \"in_compilation\": %zu", offsetof(zend_compiler_globals, in_compilation));
    fprintf(layouts, ", \"short_tags\": %zu", offsetof(zend_compiler_globals, short_tags));
    fprintf(layouts, ", \"unclean_shutdown\": %zu", offsetof(zend_compiler_globals, unclean_shutdown));
    fprintf(layouts, ", \"ini_parser_unbuffered_errors\": %zu", offsetof(zend_compiler_globals, ini_parser_unbuffered_errors));
    fprintf(layouts, ", \"open_files\": %zu", offsetof(zend_compiler_globals, open_files));
    fprintf(layouts, ", \"ini_parser_param\": %zu", offsetof(zend_compiler_globals, ini_parser_param));
    fprintf(layouts, ", \"skip_shebang\": %zu", offsetof(zend_compiler_globals, skip_shebang));
    fprintf(layouts, ", \"increment_lineno\": %zu", offsetof(zend_compiler_globals, increment_lineno));
    fprintf(layouts, ", \"variable_width_locale\": %zu", offsetof(zend_compiler_globals, variable_width_locale));
    fprintf(layouts, ", \"ascii_compatible_locale\": %zu", offsetof(zend_compiler_globals, ascii_compatible_locale));
    fprintf(layouts, ", \"doc_comment\": %zu", offsetof(zend_compiler_globals, doc_comment));
    fprintf(layouts, ", \"extra_fn_flags\": %zu", offsetof(zend_compiler_globals, extra_fn_flags));
    fprintf(layouts, ", \"compiler_options\": %zu", offsetof(zend_compiler_globals, compiler_options));
    fprintf(layouts, ", \"context\": %zu", offsetof(zend_compiler_globals, context));
    fprintf(layouts, ", \"file_context\": %zu", offsetof(zend_compiler_globals, file_context));
    fprintf(layouts, ", \"arena\": %zu", offsetof(zend_compiler_globals, arena));
    fprintf(layouts, ", \"interned_strings\": %zu", offsetof(zend_compiler_globals, interned_strings));
    fprintf(layouts, ", \"script_encoding_list\": %zu", offsetof(zend_compiler_globals, script_encoding_list));
    fprintf(layouts, ", \"script_encoding_list_size\": %zu", offsetof(zend_compiler_globals, script_encoding_list_size));
    fprintf(layouts, ", \"multibyte\": %zu", offsetof(zend_compiler_globals, multibyte));
    fprintf(layouts, ", \"detect_unicode\": %zu", offsetof(zend_compiler_globals, detect_unicode));
    fprintf(layouts, ", \"encoding_declared\": %zu", offsetof(zend_compiler_globals, encoding_declared));
    fprintf(layouts, ", \"ast\": %zu", offsetof(zend_compiler_globals, ast));
    fprintf(layouts, ", \"ast_arena\": %zu", offsetof(zend_compiler_globals, ast_arena));
    fprintf(layouts, ", \"delayed_oplines_stack\": %zu", offsetof(zend_compiler_globals, delayed_oplines_stack));
    fprintf(layouts, ", \"memoized_exprs\": %zu", offsetof(zend_compiler_globals, memoized_exprs));
    fprintf(layouts, ", \"memoize_mode\": %zu", offsetof(zend_compiler_globals, memoize_mode));
    fprintf(layouts, ", \"map_ptr_real_base\": %zu", offsetof(zend_compiler_globals, map_ptr_real_base));
    fprintf(layouts, ", \"map_ptr_base\": %zu", offsetof(zend_compiler_globals, map_ptr_base));
    fprintf(layouts, ", \"map_ptr_size\": %zu", offsetof(zend_compiler_globals, map_ptr_size));
    fprintf(layouts, ", \"map_ptr_last\": %zu", offsetof(zend_compiler_globals, map_ptr_last));
    fprintf(layouts, ", \"delayed_variance_obligations\": %zu", offsetof(zend_compiler_globals, delayed_variance_obligations));
    fprintf(layouts, ", \"delayed_autoloads\": %zu", offsetof(zend_compiler_globals, delayed_autoloads));
    fprintf(layouts, ", \"unlinked_uses\": %zu", offsetof(zend_compiler_globals, unlinked_uses));
    fprintf(layouts, ", \"current_linking_class\": %zu", offsetof(zend_compiler_globals, current_linking_class));
    fprintf(layouts, ", \"rtd_key_counter\": %zu", offsetof(zend_compiler_globals, rtd_key_counter));
    fprintf(layouts, ", \"internal_run_time_cache\": %zu", offsetof(zend_compiler_globals, internal_run_time_cache));
    fprintf(layouts, ", \"internal_run_time_cache_size\": %zu", offsetof(zend_compiler_globals, internal_run_time_cache_size));
    fprintf(layouts, ", \"short_circuiting_opnums\": %zu", offsetof(zend_compiler_globals, short_circuiting_opnums));
    fputs("}},\n", layouts);
    fputs("        \"zend_module_entry\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_module_entry));
    fprintf(layouts, "\"size\": %zu", offsetof(zend_module_entry, size));
    fprintf(layouts, ", \"zend_api\": %zu", offsetof(zend_module_entry, zend_api));
    fprintf(layouts, ", \"zend_debug\": %zu", offsetof(zend_module_entry, zend_debug));
    fprintf(layouts, ", \"zts\": %zu", offsetof(zend_module_entry, zts));
    fprintf(layouts, ", \"ini_entry\": %zu", offsetof(zend_module_entry, ini_entry));
    fprintf(layouts, ", \"deps\": %zu", offsetof(zend_module_entry, deps));
    fprintf(layouts, ", \"name\": %zu", offsetof(zend_module_entry, name));
    fprintf(layouts, ", \"functions\": %zu", offsetof(zend_module_entry, functions));
    fprintf(layouts, ", \"module_startup_func\": %zu", offsetof(zend_module_entry, module_startup_func));
    fprintf(layouts, ", \"module_shutdown_func\": %zu", offsetof(zend_module_entry, module_shutdown_func));
    fprintf(layouts, ", \"request_startup_func\": %zu", offsetof(zend_module_entry, request_startup_func));
    fprintf(layouts, ", \"request_shutdown_func\": %zu", offsetof(zend_module_entry, request_shutdown_func));
    fprintf(layouts, ", \"info_func\": %zu", offsetof(zend_module_entry, info_func));
    fprintf(layouts, ", \"version\": %zu", offsetof(zend_module_entry, version));
    fprintf(layouts, ", \"globals_size\": %zu", offsetof(zend_module_entry, globals_size));
    fprintf(layouts, ", \"globals_ptr\": %zu", offsetof(zend_module_entry, globals_ptr));
    fprintf(layouts, ", \"globals_ctor\": %zu", offsetof(zend_module_entry, globals_ctor));
    fprintf(layouts, ", \"globals_dtor\": %zu", offsetof(zend_module_entry, globals_dtor));
    fprintf(layouts, ", \"post_deactivate_func\": %zu", offsetof(zend_module_entry, post_deactivate_func));
    fprintf(layouts, ", \"module_started\": %zu", offsetof(zend_module_entry, module_started));
    fprintf(layouts, ", \"type\": %zu", offsetof(zend_module_entry, type));
    fprintf(layouts, ", \"handle\": %zu", offsetof(zend_module_entry, handle));
    fprintf(layouts, ", \"module_number\": %zu", offsetof(zend_module_entry, module_number));
    fprintf(layouts, ", \"build_id\": %zu", offsetof(zend_module_entry, build_id));
    fputs("}},\n", layouts);
    fputs("        \"zend_module_dep\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_module_dep));
    fprintf(layouts, "\"name\": %zu", offsetof(zend_module_dep, name));
    fprintf(layouts, ", \"rel\": %zu", offsetof(zend_module_dep, rel));
    fprintf(layouts, ", \"version\": %zu", offsetof(zend_module_dep, version));
    fprintf(layouts, ", \"type\": %zu", offsetof(zend_module_dep, type));
    fputs("}},\n", layouts);
    fputs("        \"zend_object_handlers\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_object_handlers));
    fprintf(layouts, "\"offset\": %zu", offsetof(zend_object_handlers, offset));
    fprintf(layouts, ", \"free_obj\": %zu", offsetof(zend_object_handlers, free_obj));
    fprintf(layouts, ", \"dtor_obj\": %zu", offsetof(zend_object_handlers, dtor_obj));
    fprintf(layouts, ", \"clone_obj\": %zu", offsetof(zend_object_handlers, clone_obj));
    fprintf(layouts, ", \"read_property\": %zu", offsetof(zend_object_handlers, read_property));
    fprintf(layouts, ", \"write_property\": %zu", offsetof(zend_object_handlers, write_property));
    fprintf(layouts, ", \"read_dimension\": %zu", offsetof(zend_object_handlers, read_dimension));
    fprintf(layouts, ", \"write_dimension\": %zu", offsetof(zend_object_handlers, write_dimension));
    fprintf(layouts, ", \"get_property_ptr_ptr\": %zu", offsetof(zend_object_handlers, get_property_ptr_ptr));
    fprintf(layouts, ", \"has_property\": %zu", offsetof(zend_object_handlers, has_property));
    fprintf(layouts, ", \"unset_property\": %zu", offsetof(zend_object_handlers, unset_property));
    fprintf(layouts, ", \"has_dimension\": %zu", offsetof(zend_object_handlers, has_dimension));
    fprintf(layouts, ", \"unset_dimension\": %zu", offsetof(zend_object_handlers, unset_dimension));
    fprintf(layouts, ", \"get_properties\": %zu", offsetof(zend_object_handlers, get_properties));
    fprintf(layouts, ", \"get_method\": %zu", offsetof(zend_object_handlers, get_method));
    fprintf(layouts, ", \"get_constructor\": %zu", offsetof(zend_object_handlers, get_constructor));
    fprintf(layouts, ", \"get_class_name\": %zu", offsetof(zend_object_handlers, get_class_name));
    fprintf(layouts, ", \"cast_object\": %zu", offsetof(zend_object_handlers, cast_object));
    fprintf(layouts, ", \"count_elements\": %zu", offsetof(zend_object_handlers, count_elements));
    fprintf(layouts, ", \"get_debug_info\": %zu", offsetof(zend_object_handlers, get_debug_info));
    fprintf(layouts, ", \"get_closure\": %zu", offsetof(zend_object_handlers, get_closure));
    fprintf(layouts, ", \"get_gc\": %zu", offsetof(zend_object_handlers, get_gc));
    fprintf(layouts, ", \"do_operation\": %zu", offsetof(zend_object_handlers, do_operation));
    fprintf(layouts, ", \"compare\": %zu", offsetof(zend_object_handlers, compare));
    fprintf(layouts, ", \"get_properties_for\": %zu", offsetof(zend_object_handlers, get_properties_for));
    fputs("}},\n", layouts);
    fputs("        \"zend_object_iterator\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_object_iterator));
    fprintf(layouts, "\"std\": %zu", offsetof(zend_object_iterator, std));
    fprintf(layouts, ", \"data\": %zu", offsetof(zend_object_iterator, data));
    fprintf(layouts, ", \"funcs\": %zu", offsetof(zend_object_iterator, funcs));
    fprintf(layouts, ", \"index\": %zu", offsetof(zend_object_iterator, index));
    fputs("}},\n", layouts);
    fputs("        \"zend_object_iterator_funcs\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_object_iterator_funcs));
    fprintf(layouts, "\"dtor\": %zu", offsetof(zend_object_iterator_funcs, dtor));
    fprintf(layouts, ", \"valid\": %zu", offsetof(zend_object_iterator_funcs, valid));
    fprintf(layouts, ", \"get_current_data\": %zu", offsetof(zend_object_iterator_funcs, get_current_data));
    fprintf(layouts, ", \"get_current_key\": %zu", offsetof(zend_object_iterator_funcs, get_current_key));
    fprintf(layouts, ", \"move_forward\": %zu", offsetof(zend_object_iterator_funcs, move_forward));
    fprintf(layouts, ", \"rewind\": %zu", offsetof(zend_object_iterator_funcs, rewind));
    fprintf(layouts, ", \"invalidate_current\": %zu", offsetof(zend_object_iterator_funcs, invalidate_current));
    fprintf(layouts, ", \"get_gc\": %zu", offsetof(zend_object_iterator_funcs, get_gc));
    fputs("}},\n", layouts);
    fputs("        \"zend_ast\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_ast));
    fprintf(layouts, "\"kind\": %zu", offsetof(zend_ast, kind));
    fprintf(layouts, ", \"attr\": %zu", offsetof(zend_ast, attr));
    fprintf(layouts, ", \"lineno\": %zu", offsetof(zend_ast, lineno));
    fprintf(layouts, ", \"child\": %zu", offsetof(zend_ast, child));
    fputs("}},\n", layouts);
    fputs("        \"zend_ast_decl\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_ast_decl));
    fprintf(layouts, "\"kind\": %zu", offsetof(zend_ast_decl, kind));
    fprintf(layouts, ", \"attr\": %zu", offsetof(zend_ast_decl, attr));
    fprintf(layouts, ", \"start_lineno\": %zu", offsetof(zend_ast_decl, start_lineno));
    fprintf(layouts, ", \"end_lineno\": %zu", offsetof(zend_ast_decl, end_lineno));
    fprintf(layouts, ", \"flags\": %zu", offsetof(zend_ast_decl, flags));
    fprintf(layouts, ", \"doc_comment\": %zu", offsetof(zend_ast_decl, doc_comment));
    fprintf(layouts, ", \"name\": %zu", offsetof(zend_ast_decl, name));
    fprintf(layouts, ", \"child\": %zu", offsetof(zend_ast_decl, child));
    fputs("}},\n", layouts);
    fputs("        \"zend_ast_list\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_ast_list));
    fprintf(layouts, "\"kind\": %zu", offsetof(zend_ast_list, kind));
    fprintf(layouts, ", \"attr\": %zu", offsetof(zend_ast_list, attr));
    fprintf(layouts, ", \"lineno\": %zu", offsetof(zend_ast_list, lineno));
    fprintf(layouts, ", \"children\": %zu", offsetof(zend_ast_list, children));
    fprintf(layouts, ", \"child\": %zu", offsetof(zend_ast_list, child));
    fputs("}},\n", layouts);
    fputs("        \"zend_ast_zval\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_ast_zval));
    fprintf(layouts, "\"kind\": %zu", offsetof(zend_ast_zval, kind));
    fprintf(layouts, ", \"attr\": %zu", offsetof(zend_ast_zval, attr));
    fprintf(layouts, ", \"val\": %zu", offsetof(zend_ast_zval, val));
    fputs("}},\n", layouts);
    fputs("        \"zend_lex_state\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_lex_state));
    fprintf(layouts, "\"yy_leng\": %zu", offsetof(zend_lex_state, yy_leng));
    fprintf(layouts, ", \"yy_start\": %zu", offsetof(zend_lex_state, yy_start));
    fprintf(layouts, ", \"yy_text\": %zu", offsetof(zend_lex_state, yy_text));
    fprintf(layouts, ", \"yy_cursor\": %zu", offsetof(zend_lex_state, yy_cursor));
    fprintf(layouts, ", \"yy_marker\": %zu", offsetof(zend_lex_state, yy_marker));
    fprintf(layouts, ", \"yy_limit\": %zu", offsetof(zend_lex_state, yy_limit));
    fprintf(layouts, ", \"yy_state\": %zu", offsetof(zend_lex_state, yy_state));
    fprintf(layouts, ", \"state_stack\": %zu", offsetof(zend_lex_state, state_stack));
    fprintf(layouts, ", \"heredoc_label_stack\": %zu", offsetof(zend_lex_state, heredoc_label_stack));
    fprintf(layouts, ", \"nest_location_stack\": %zu", offsetof(zend_lex_state, nest_location_stack));
    fprintf(layouts, ", \"in\": %zu", offsetof(zend_lex_state, in));
    fprintf(layouts, ", \"lineno\": %zu", offsetof(zend_lex_state, lineno));
    fprintf(layouts, ", \"filename\": %zu", offsetof(zend_lex_state, filename));
    fprintf(layouts, ", \"script_org\": %zu", offsetof(zend_lex_state, script_org));
    fprintf(layouts, ", \"script_org_size\": %zu", offsetof(zend_lex_state, script_org_size));
    fprintf(layouts, ", \"script_filtered\": %zu", offsetof(zend_lex_state, script_filtered));
    fprintf(layouts, ", \"script_filtered_size\": %zu", offsetof(zend_lex_state, script_filtered_size));
    fprintf(layouts, ", \"input_filter\": %zu", offsetof(zend_lex_state, input_filter));
    fprintf(layouts, ", \"output_filter\": %zu", offsetof(zend_lex_state, output_filter));
    fprintf(layouts, ", \"script_encoding\": %zu", offsetof(zend_lex_state, script_encoding));
    fprintf(layouts, ", \"on_event\": %zu", offsetof(zend_lex_state, on_event));
    fprintf(layouts, ", \"on_event_context\": %zu", offsetof(zend_lex_state, on_event_context));
    fprintf(layouts, ", \"ast\": %zu", offsetof(zend_lex_state, ast));
    fprintf(layouts, ", \"ast_arena\": %zu", offsetof(zend_lex_state, ast_arena));
    fputs("}},\n", layouts);
    fputs("        \"zend_closure\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_closure));
    fprintf(layouts, "\"std\": %zu", offsetof(zend_closure, std));
    fprintf(layouts, ", \"func\": %zu", offsetof(zend_closure, func));
    fprintf(layouts, ", \"this_ptr\": %zu", offsetof(zend_closure, this_ptr));
    fprintf(layouts, ", \"called_scope\": %zu", offsetof(zend_closure, called_scope));
    fprintf(layouts, ", \"orig_internal_handler\": %zu", offsetof(zend_closure, orig_internal_handler));
    fputs("}},\n", layouts);
    fputs("        \"zend_script\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_script));
    fprintf(layouts, "\"filename\": %zu", offsetof(zend_script, filename));
    fprintf(layouts, ", \"main_op_array\": %zu", offsetof(zend_script, main_op_array));
    fprintf(layouts, ", \"function_table\": %zu", offsetof(zend_script, function_table));
    fprintf(layouts, ", \"class_table\": %zu", offsetof(zend_script, class_table));
    fputs("}},\n", layouts);
    fputs("        \"zend_error_info\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_error_info));
    fprintf(layouts, "\"type\": %zu", offsetof(zend_error_info, type));
    fprintf(layouts, ", \"lineno\": %zu", offsetof(zend_error_info, lineno));
    fprintf(layouts, ", \"filename\": %zu", offsetof(zend_error_info, filename));
    fprintf(layouts, ", \"message\": %zu", offsetof(zend_error_info, message));
    fputs("}},\n", layouts);
    fputs("        \"zend_early_binding\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_early_binding));
    fprintf(layouts, "\"lcname\": %zu", offsetof(zend_early_binding, lcname));
    fprintf(layouts, ", \"rtd_key\": %zu", offsetof(zend_early_binding, rtd_key));
    fprintf(layouts, ", \"lc_parent_name\": %zu", offsetof(zend_early_binding, lc_parent_name));
    fprintf(layouts, ", \"cache_slot\": %zu", offsetof(zend_early_binding, cache_slot));
    fputs("}},\n", layouts);
    fputs("        \"zend_persistent_script\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_persistent_script));
    fprintf(layouts, "\"script\": %zu", offsetof(zend_persistent_script, script));
    fprintf(layouts, ", \"compiler_halt_offset\": %zu", offsetof(zend_persistent_script, compiler_halt_offset));
    fprintf(layouts, ", \"ping_auto_globals_mask\": %zu", offsetof(zend_persistent_script, ping_auto_globals_mask));
    fprintf(layouts, ", \"timestamp\": %zu", offsetof(zend_persistent_script, timestamp));
    fprintf(layouts, ", \"corrupted\": %zu", offsetof(zend_persistent_script, corrupted));
    fprintf(layouts, ", \"is_phar\": %zu", offsetof(zend_persistent_script, is_phar));
    fprintf(layouts, ", \"empty\": %zu", offsetof(zend_persistent_script, empty));
    fprintf(layouts, ", \"num_warnings\": %zu", offsetof(zend_persistent_script, num_warnings));
    fprintf(layouts, ", \"num_early_bindings\": %zu", offsetof(zend_persistent_script, num_early_bindings));
    fprintf(layouts, ", \"warnings\": %zu", offsetof(zend_persistent_script, warnings));
    fprintf(layouts, ", \"early_bindings\": %zu", offsetof(zend_persistent_script, early_bindings));
    fprintf(layouts, ", \"mem\": %zu", offsetof(zend_persistent_script, mem));
    fprintf(layouts, ", \"size\": %zu", offsetof(zend_persistent_script, size));
    fprintf(layouts, ", \"dynamic_members\": %zu", offsetof(zend_persistent_script, dynamic_members));
    fputs("}},\n", layouts);
    fputs("        \"zend_file_cache_metainfo\": {", layouts);
    fprintf(layouts, "\"size\": %zu, \"fields\": {", sizeof(zend_file_cache_metainfo));
    fprintf(layouts, "\"magic\": %zu", offsetof(zend_file_cache_metainfo, magic));
    fprintf(layouts, ", \"system_id\": %zu", offsetof(zend_file_cache_metainfo, system_id));
    fprintf(layouts, ", \"mem_size\": %zu", offsetof(zend_file_cache_metainfo, mem_size));
    fprintf(layouts, ", \"str_size\": %zu", offsetof(zend_file_cache_metainfo, str_size));
    fprintf(layouts, ", \"script_offset\": %zu", offsetof(zend_file_cache_metainfo, script_offset));
    fprintf(layouts, ", \"timestamp\": %zu", offsetof(zend_file_cache_metainfo, timestamp));
    fprintf(layouts, ", \"checksum\": %zu", offsetof(zend_file_cache_metainfo, checksum));
    fputs("}}\n", layouts);
    fputs("    }\n}\n", layouts);
    fclose(layouts);
    return 0;
}
