<?php

declare(strict_types=1);

namespace ZEngine\Generator;

use RuntimeException;

/**
 * Generates, compiles and runs the C probe program that extracts ground-truth
 * data invisible to (or not trustable from) FFI:
 *
 *   - constants.php: values of #define macros, enum members and opcodes
 *   - layouts.json:  sizeof/offsetof of every struct the PHP code dereferences,
 *                    measured by the reference C compiler
 */
final class ProbeGenerator
{
    /**
     * @param list<string>          $defines       macro names (missing ones are skipped via #ifdef)
     * @param array<string, list<string>> $enumMembers  enum tag => member names
     * @param array<string, string> $opcodes       opcode name => numeric value (parsed from zend_vm_opcodes.h)
     * @param array<string, list<string>> $layoutFields  struct type name => offsetof-safe field names
     * @param array<string, bool>   $layoutIsUnion struct type name => is a union
     */
    public function __construct(
        private readonly array $defines,
        private readonly array $enumMembers,
        private readonly array $opcodes,
        private readonly array $layoutFields,
        private readonly array $layoutIsUnion,
    ) {
    }

    public function generateProbeSource(string $supplementFile): string
    {
        $lines   = [];
        $lines[] = '#include "php.h"';
        $lines[] = '#include "zend_ast.h"';
        $lines[] = '#include "zend_language_scanner.h"';
        $lines[] = '#include "zend_inheritance.h"';
        $lines[] = '#include "zend_hash.h"';
        $lines[] = '#include "zend_modules.h"';
        $lines[] = '#include "zend_arena.h"';
        if ($supplementFile !== '') {
            $lines[] = '#include "' . basename($supplementFile) . '"';
        }
        $lines[] = '#include <stdio.h>';
        $lines[] = '';
        $lines[] = 'int main(void) {';
        $lines[] = '    FILE *constants = fopen("constants.php", "w");';
        $lines[] = '    FILE *layouts   = fopen("layouts.json", "w");';
        $lines[] = '    if (!constants || !layouts) { return 1; }';
        $lines[] = '    fputs("<?php\n\n/* Generated by tools/generator - DO NOT EDIT */\n\nreturn [\n", constants);';

        foreach ($this->defines as $define) {
            $lines[] = "#ifdef {$define}";
            $lines[] = "    fprintf(constants, \"    '{$define}' => %lld,\\n\", (long long)({$define}));";
            $lines[] = "#endif";
        }
        foreach ($this->enumMembers as $members) {
            foreach ($members as $member) {
                $lines[] = "    fprintf(constants, \"    '{$member}' => %lld,\\n\", (long long)({$member}));";
            }
        }
        foreach ($this->opcodes as $opcode => $value) {
            $lines[] = "    fprintf(constants, \"    '{$opcode}' => {$value},\\n\");";
        }
        $lines[] = '    fputs("];\n", constants);';
        $lines[] = '    fclose(constants);';
        $lines[] = '';

        $lines[] = '    fputs("{\n", layouts);';
        // Only the minor version is recorded: ABI is stable within a minor and
        // recording the patch level would make the CI drift check fail on
        // every patch release.
        $lines[] = '    fprintf(layouts, "    \"meta\": {\"php\": \"%d.%d\", \"api\": %d, \"zts\": %d, \"debug\": %d},\n", PHP_MAJOR_VERSION, PHP_MINOR_VERSION, ZEND_MODULE_API_NO, (int)USING_ZTS, (int)ZEND_DEBUG);';
        $lines[] = '    fputs("    \"structs\": {\n", layouts);';
        $structNames = array_keys($this->layoutFields);
        $lastStruct  = end($structNames);
        foreach ($this->layoutFields as $struct => $fields) {
            $isUnion = $this->layoutIsUnion[$struct] ?? false;
            $lines[] = "    fputs(\"        \\\"{$struct}\\\": {\", layouts);";
            $lines[] = "    fprintf(layouts, \"\\\"size\\\": %zu, \\\"fields\\\": {\", sizeof({$struct}));";
            if (!$isUnion) {
                $separator = '';
                foreach ($fields as $field) {
                    $lines[]   = "    fprintf(layouts, \"{$separator}\\\"{$field}\\\": %zu\", offsetof({$struct}, {$field}));";
                    $separator = ', ';
                }
            }
            $suffix  = $struct === $lastStruct ? '}}\n' : '}},\n';
            $lines[] = "    fputs(\"{$suffix}\", layouts);";
        }
        $lines[] = '    fputs("    }\n}\n", layouts);';
        $lines[] = '    fclose(layouts);';
        $lines[] = '    return 0;';
        $lines[] = '}';

        return implode("\n", $lines) . "\n";
    }

    /**
     * Parses ZEND_<OPCODE> defines out of zend_vm_opcodes.h (they are plain
     * integer literals there, including ZEND_VM_LAST_OPCODE).
     *
     * @return array<string, string>
     */
    public static function parseOpcodes(string $vmOpcodesHeaderPath): array
    {
        $contents = file_get_contents($vmOpcodesHeaderPath);
        if ($contents === false) {
            throw new RuntimeException("Cannot read {$vmOpcodesHeaderPath}");
        }
        preg_match_all('/^#\s*define\s+(ZEND_[A-Z0-9_]+)\s+(\d+)\s*$/m', $contents, $matches, PREG_SET_ORDER);
        $opcodes = [];
        foreach ($matches as $match) {
            // Skip non-opcode helper defines like ZEND_VM_KIND_*
            if (str_starts_with($match[1], 'ZEND_VM_KIND')) {
                continue;
            }
            $opcodes[$match[1]] = $match[2];
        }
        if ($opcodes === []) {
            throw new RuntimeException("No opcodes parsed from {$vmOpcodesHeaderPath}");
        }

        return $opcodes;
    }
}
