<?php

/*
 * Generated by tools/generator for PHP 8.4 - DO NOT EDIT.
 * Regenerate with `composer gen-headers`.
 *
 * Analysis-only stub classes for the Zend Engine structs: every C field is a
 * real typed public property, so PHPStan (via scanFiles) and the IDE resolve
 * and autocomplete engine struct access statically. The runtime values remain
 * FFI\CData handles: these classes are never loadable (stubs/ is outside the
 * PSR-4 roots), never instantiated and never instanceof'd - the only legal
 * runtime use is the ::class constant, which does not trigger autoloading.
 *
 * The file is byte-identical across all supported targets: fields that exist
 * only on some targets (#ifdef'd engine fields) are listed in
 * tools/generator/symbols.php 'stub_platform_fields' and omitted everywhere.
 */

declare(strict_types=1);

namespace ZEngine\Generated;

/**
 * Analysis-only view of the engine C struct 'Bucket'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class Bucket implements \ArrayAccess
{
    public zval $val;
    public int $h;
    public ?zend_string $key;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'HashTable'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class HashTable implements \ArrayAccess
{
    public zend_refcounted_h $gc;
    public HashTable_u $u;
    public int $nTableMask;
    public ?\FFI\CData $arHash;
    public ?Bucket $arData;
    public ?zval $arPacked;
    public int $nNumUsed;
    public int $nNumOfElements;
    public int $nTableSize;
    public int $nInternalPointer;
    public int $nNextFreeElement;
    public \FFI\CData|\Closure|null $pDestructor;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'HashTableIterator'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class HashTableIterator implements \ArrayAccess
{
    public ?HashTable $ht;
    public int $pos;
    public int $next_copy;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'HashTable.u'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class HashTable_u implements \ArrayAccess
{
    public HashTable_u_v $v;
    public int $flags;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'HashTable.u.v'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class HashTable_u_v implements \ArrayAccess
{
    public int $flags;
    public int $_unused;
    public int $nIteratorsCount;
    public int $_unused2;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct '_zend_function_entry'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class _zend_function_entry implements \ArrayAccess
{
    public ?\FFI\CData $fname;
    public \FFI\CData|\Closure|null $handler;
    public ?zend_internal_arg_info $arg_info;
    public int $num_args;
    public int $flags;
    public ?zend_frameless_function_info $frameless_function_infos;
    public ?\FFI\CData $doc_comment;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct '_zend_ini_parser_param'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class _zend_ini_parser_param implements \ArrayAccess
{
    public \FFI\CData|\Closure|null $ini_parser_cb;
    public ?\FFI\CData $arg;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct '_zend_vm_stack'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class _zend_vm_stack implements \ArrayAccess
{
    public ?zval $top;
    public ?zval $end;
    public ?_zend_vm_stack $prev;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_arena'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_arena implements \ArrayAccess
{
    public ?\FFI\CData $ptr;
    public ?\FFI\CData $end;
    public ?zend_arena $prev;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_arg_info'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_arg_info implements \ArrayAccess
{
    public ?zend_string $name;
    public zend_type $type;
    public ?zend_string $default_value;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_array'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_array implements \ArrayAccess
{
    public zend_refcounted_h $gc;
    public zend_array_u $u;
    public int $nTableMask;
    public ?\FFI\CData $arHash;
    public ?Bucket $arData;
    public ?zval $arPacked;
    public int $nNumUsed;
    public int $nNumOfElements;
    public int $nTableSize;
    public int $nInternalPointer;
    public int $nNextFreeElement;
    public \FFI\CData|\Closure|null $pDestructor;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zend_array.u'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_array_u implements \ArrayAccess
{
    public zend_array_u_v $v;
    public int $flags;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_array.u.v'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_array_u_v implements \ArrayAccess
{
    public int $flags;
    public int $_unused;
    public int $nIteratorsCount;
    public int $_unused2;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_ast'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_ast implements \ArrayAccess
{
    public int $kind;
    public int $attr;
    public int $lineno;
    public \FFI\CData $child;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_ast_decl'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_ast_decl implements \ArrayAccess
{
    public int $kind;
    public int $attr;
    public int $start_lineno;
    public int $end_lineno;
    public int $flags;
    public ?zend_string $doc_comment;
    public ?zend_string $name;
    public \FFI\CData $child;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_ast_list'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_ast_list implements \ArrayAccess
{
    public int $kind;
    public int $attr;
    public int $lineno;
    public int $children;
    public \FFI\CData $child;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_ast_ref'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_ast_ref implements \ArrayAccess
{
    public zend_refcounted_h $gc;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_ast_zval'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_ast_zval implements \ArrayAccess
{
    public int $kind;
    public int $attr;
    public zval $val;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_atomic_bool'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_atomic_bool implements \ArrayAccess
{
    public \FFI\CData $value;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_attribute'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_attribute implements \ArrayAccess
{
    public ?zend_string $name;
    public ?zend_string $lcname;
    public int $flags;
    public int $lineno;
    public int $offset;
    public int $argc;
    public \FFI\CData $args;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_attribute_arg'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_attribute_arg implements \ArrayAccess
{
    public ?zend_string $name;
    public zval $value;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_brk_cont_element'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_brk_cont_element implements \ArrayAccess
{
    public int $start;
    public int $cont;
    public int $brk;
    public int $parent;
    public bool $is_switch;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_call_stack'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_call_stack implements \ArrayAccess
{
    public ?\FFI\CData $base;
    public int $max_size;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_arrayaccess_funcs'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_arrayaccess_funcs implements \ArrayAccess
{
    public ?zend_function $zf_offsetget;
    public ?zend_function $zf_offsetexists;
    public ?zend_function $zf_offsetset;
    public ?zend_function $zf_offsetunset;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_constant'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_constant implements \ArrayAccess
{
    public zval $value;
    public ?zend_string $doc_comment;
    public ?HashTable $attributes;
    public ?zend_class_entry $ce;
    public zend_type $type;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_dependency'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_dependency implements \ArrayAccess
{
    public ?zend_string $name;
    public ?zend_class_entry $ce;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_entry'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_entry implements \ArrayAccess
{
    public string $type;
    public ?zend_string $name;
    public ?zend_class_entry $parent;
    public ?zend_string $parent_name;
    public int $refcount;
    public int $ce_flags;
    public int $default_properties_count;
    public int $default_static_members_count;
    public ?zval $default_properties_table;
    public ?zval $default_static_members_table;
    public ?zval $static_members_table__ptr;
    public HashTable $function_table;
    public HashTable $properties_info;
    public HashTable $constants_table;
    public ?zend_class_mutable_data $mutable_data__ptr;
    public ?zend_inheritance_cache_entry $inheritance_cache;
    public ?\FFI\CData $properties_info_table;
    public ?zend_function $constructor;
    public ?zend_function $destructor;
    public ?zend_function $clone;
    public ?zend_function $__get;
    public ?zend_function $__set;
    public ?zend_function $__unset;
    public ?zend_function $__isset;
    public ?zend_function $__call;
    public ?zend_function $__callstatic;
    public ?zend_function $__tostring;
    public ?zend_function $__debugInfo;
    public ?zend_function $__serialize;
    public ?zend_function $__unserialize;
    public ?zend_object_handlers $default_object_handlers;
    public ?zend_class_iterator_funcs $iterator_funcs_ptr;
    public ?zend_class_arrayaccess_funcs $arrayaccess_funcs_ptr;
    public \FFI\CData|\Closure|null $create_object;
    public \FFI\CData|\Closure|null $interface_gets_implemented;
    public \FFI\CData|\Closure|null $get_iterator;
    public \FFI\CData|\Closure|null $get_static_method;
    public \FFI\CData|\Closure|null $serialize;
    public \FFI\CData|\Closure|null $unserialize;
    public int $num_interfaces;
    public int $num_traits;
    public int $num_hooked_props;
    public int $num_hooked_prop_variance_checks;
    public ?\FFI\CData $interfaces;
    public ?zend_class_name $interface_names;
    public ?zend_class_name $trait_names;
    public ?\FFI\CData $trait_aliases;
    public ?\FFI\CData $trait_precedences;
    public ?HashTable $attributes;
    public int $enum_backing_type;
    public ?HashTable $backed_enum_table;
    public ?zend_string $doc_comment;
    public zend_class_entry_info $info;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zend_class_entry.info'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_entry_info implements \ArrayAccess
{
    public zend_class_entry_info_user $user;
    public zend_class_entry_info_internal $internal;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_entry.info.internal'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_entry_info_internal implements \ArrayAccess
{
    public ?_zend_function_entry $builtin_functions;
    public ?zend_module_entry $module;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_entry.info.user'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_entry_info_user implements \ArrayAccess
{
    public ?zend_string $filename;
    public int $line_start;
    public int $line_end;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_iterator_funcs'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_iterator_funcs implements \ArrayAccess
{
    public ?zend_function $zf_new_iterator;
    public ?zend_function $zf_valid;
    public ?zend_function $zf_current;
    public ?zend_function $zf_key;
    public ?zend_function $zf_next;
    public ?zend_function $zf_rewind;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_mutable_data'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_mutable_data implements \ArrayAccess
{
    public ?zval $default_properties_table;
    public ?HashTable $constants_table;
    public int $ce_flags;
    public ?HashTable $backed_enum_table;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_class_name'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_class_name implements \ArrayAccess
{
    public ?zend_string $name;
    public ?zend_string $lc_name;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_closure'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_closure implements \ArrayAccess
{
    public zend_object $std;
    public zend_function $func;
    public zval $this_ptr;
    public ?zend_class_entry $called_scope;
    public \FFI\CData|\Closure|null $orig_internal_handler;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_compiler_globals'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_compiler_globals implements \ArrayAccess
{
    public zend_stack $loop_var_stack;
    public ?zend_class_entry $active_class_entry;
    public ?zend_string $compiled_filename;
    public int $zend_lineno;
    public ?zend_op_array $active_op_array;
    public ?HashTable $function_table;
    public ?HashTable $class_table;
    public ?HashTable $auto_globals;
    public int $parse_error;
    public bool $in_compilation;
    public bool $short_tags;
    public bool $unclean_shutdown;
    public bool $ini_parser_unbuffered_errors;
    public zend_llist $open_files;
    public ?_zend_ini_parser_param $ini_parser_param;
    public bool $skip_shebang;
    public bool $increment_lineno;
    public bool $variable_width_locale;
    public bool $ascii_compatible_locale;
    public ?zend_string $doc_comment;
    public int $extra_fn_flags;
    public int $compiler_options;
    public zend_oparray_context $context;
    public zend_file_context $file_context;
    public ?zend_arena $arena;
    public HashTable $interned_strings;
    public ?\FFI\CData $script_encoding_list;
    public int $script_encoding_list_size;
    public bool $multibyte;
    public bool $detect_unicode;
    public bool $encoding_declared;
    public ?zend_ast $ast;
    public ?zend_arena $ast_arena;
    public zend_stack $delayed_oplines_stack;
    public ?HashTable $memoized_exprs;
    public int $memoize_mode;
    public ?\FFI\CData $map_ptr_real_base;
    public ?\FFI\CData $map_ptr_base;
    public int $map_ptr_size;
    public int $map_ptr_last;
    public ?HashTable $delayed_variance_obligations;
    public ?HashTable $delayed_autoloads;
    public ?HashTable $unlinked_uses;
    public ?zend_class_entry $current_linking_class;
    public int $rtd_key_counter;
    public ?\FFI\CData $internal_run_time_cache;
    public int $internal_run_time_cache_size;
    public zend_stack $short_circuiting_opnums;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_constant'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_constant implements \ArrayAccess
{
    public zval $value;
    public ?zend_string $name;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_declarables'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_declarables implements \ArrayAccess
{
    public int $ticks;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_early_binding'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_early_binding implements \ArrayAccess
{
    public ?zend_string $lcname;
    public ?zend_string $rtd_key;
    public ?zend_string $lc_parent_name;
    public int $cache_slot;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_error_info'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_error_info implements \ArrayAccess
{
    public int $type;
    public int $lineno;
    public ?zend_string $filename;
    public ?zend_string $message;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_execute_data'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_execute_data implements \ArrayAccess
{
    public ?zend_op $opline;
    public ?zend_execute_data $call;
    public ?zval $return_value;
    public ?zend_function $func;
    public zval $This;
    public ?zend_execute_data $prev_execute_data;
    public ?zend_array $symbol_table;
    public ?\FFI\CData $run_time_cache;
    public ?zend_array $extra_named_params;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_executor_globals'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_executor_globals implements \ArrayAccess
{
    public zval $uninitialized_zval;
    public zval $error_zval;
    public \FFI\CData $symtable_cache;
    public ?\FFI\CData $symtable_cache_limit;
    public ?\FFI\CData $symtable_cache_ptr;
    public zend_array $symbol_table;
    public HashTable $included_files;
    public ?\FFI\CData $bailout;
    public int $error_reporting;
    public int $exit_status;
    public ?HashTable $function_table;
    public ?HashTable $class_table;
    public ?HashTable $zend_constants;
    public ?zval $vm_stack_top;
    public ?zval $vm_stack_end;
    public ?_zend_vm_stack $vm_stack;
    public int $vm_stack_page_size;
    public ?zend_execute_data $current_execute_data;
    public ?zend_class_entry $fake_scope;
    public int $jit_trace_num;
    public ?zend_execute_data $current_observed_frame;
    public int $ticks_count;
    public int $precision;
    public int $persistent_constants_count;
    public int $persistent_functions_count;
    public int $persistent_classes_count;
    public bool $no_extensions;
    public bool $full_tables_cleanup;
    public zend_atomic_bool $vm_interrupt;
    public zend_atomic_bool $timed_out;
    public ?HashTable $in_autoload;
    public int $hard_timeout;
    public ?\FFI\CData $stack_base;
    public ?\FFI\CData $stack_limit;
    public HashTable $regular_list;
    public HashTable $persistent_list;
    public int $user_error_handler_error_reporting;
    public bool $exception_ignore_args;
    public zval $user_error_handler;
    public zval $user_exception_handler;
    public zend_stack $user_error_handlers_error_reporting;
    public zend_stack $user_error_handlers;
    public zend_stack $user_exception_handlers;
    public ?zend_class_entry $exception_class;
    public int $error_handling;
    public int $capture_warnings_during_sccp;
    public int $timeout_seconds;
    public ?HashTable $ini_directives;
    public ?HashTable $modified_ini_directives;
    public ?zend_ini_entry $error_reporting_ini_entry;
    public zend_objects_store $objects_store;
    public zend_lazy_objects_store $lazy_objects_store;
    public ?zend_object $exception;
    public ?zend_object $prev_exception;
    public ?zend_op $opline_before_exception;
    public \FFI\CData $exception_op;
    public ?zend_module_entry $current_module;
    public bool $active;
    public int $flags;
    public int $assertions;
    public int $ht_iterators_count;
    public int $ht_iterators_used;
    public ?HashTableIterator $ht_iterators;
    public \FFI\CData $ht_iterators_slots;
    public ?\FFI\CData $saved_fpu_cw_ptr;
    public zend_function $trampoline;
    public zend_op $call_trampoline_op;
    public HashTable $weakrefs;
    public int $exception_string_param_max_len;
    public zend_get_gc_buffer $get_gc_buffer;
    public ?\FFI\CData $main_fiber_context;
    public ?\FFI\CData $current_fiber_context;
    public ?\FFI\CData $active_fiber;
    public int $fiber_stack_size;
    public bool $record_errors;
    public int $num_errors;
    public ?\FFI\CData $errors;
    public ?zend_string $filename_override;
    public int $lineno_override;
    public zend_call_stack $call_stack;
    public int $max_allowed_stack_size;
    public int $reserved_stack_size;
    public zend_strtod_state $strtod_state;
    public \FFI\CData $reserved;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_file_cache_metainfo'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_file_cache_metainfo implements \ArrayAccess
{
    public \FFI\CData $magic;
    public \FFI\CData $system_id;
    public int $mem_size;
    public int $str_size;
    public int $script_offset;
    public int $timestamp;
    public int $checksum;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_file_context'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_file_context implements \ArrayAccess
{
    public zend_declarables $declarables;
    public ?zend_string $current_namespace;
    public bool $in_namespace;
    public bool $has_bracketed_namespaces;
    public ?HashTable $imports;
    public ?HashTable $imports_function;
    public ?HashTable $imports_const;
    public HashTable $seen_symbols;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_file_handle'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_file_handle implements \ArrayAccess
{
    public zend_file_handle_handle $handle;
    public ?zend_string $filename;
    public ?zend_string $opened_path;
    public int $type;
    public bool $primary_script;
    public bool $in_list;
    public ?\FFI\CData $buf;
    public int $len;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zend_file_handle.handle'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_file_handle_handle implements \ArrayAccess
{
    public ?\FFI\CData $fp;
    public zend_stream $stream;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_frameless_function_info'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_frameless_function_info implements \ArrayAccess
{
    public ?\FFI\CData $handler;
    public int $num_args;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zend_function'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_function implements \ArrayAccess
{
    public int $type;
    public int $quick_arg_flags;
    public zend_function_common $common;
    public zend_op_array $op_array;
    public zend_internal_function $internal_function;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_function.common'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_function_common implements \ArrayAccess
{
    public int $type;
    public \FFI\CData $arg_flags;
    public int $fn_flags;
    public ?zend_string $function_name;
    public ?zend_class_entry $scope;
    public ?zend_function $prototype;
    public int $num_args;
    public int $required_num_args;
    public ?zend_arg_info $arg_info;
    public ?HashTable $attributes;
    public ?\FFI\CData $run_time_cache__ptr;
    public ?zend_string $doc_comment;
    public int $T;
    public ?zend_property_info $prop_info;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_get_gc_buffer'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_get_gc_buffer implements \ArrayAccess
{
    public ?zval $cur;
    public ?zval $end;
    public ?zval $start;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_inheritance_cache_entry'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_inheritance_cache_entry implements \ArrayAccess
{
    public ?zend_inheritance_cache_entry $next;
    public ?zend_class_entry $ce;
    public ?zend_class_entry $parent;
    public ?zend_class_dependency $dependencies;
    public int $dependencies_count;
    public int $num_warnings;
    public ?\FFI\CData $warnings;
    public \FFI\CData $traits_and_interfaces;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_ini_entry'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_ini_entry implements \ArrayAccess
{
    public ?zend_string $name;
    public \FFI\CData|\Closure|null $on_modify;
    public ?\FFI\CData $mh_arg1;
    public ?\FFI\CData $mh_arg2;
    public ?\FFI\CData $mh_arg3;
    public ?zend_string $value;
    public ?zend_string $orig_value;
    public \FFI\CData|\Closure|null $displayer;
    public int $module_number;
    public int $modifiable;
    public int $orig_modifiable;
    public int $modified;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_internal_arg_info'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_internal_arg_info implements \ArrayAccess
{
    public ?\FFI\CData $name;
    public zend_type $type;
    public ?\FFI\CData $default_value;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_internal_function'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_internal_function implements \ArrayAccess
{
    public int $type;
    public \FFI\CData $arg_flags;
    public int $fn_flags;
    public ?zend_string $function_name;
    public ?zend_class_entry $scope;
    public ?zend_function $prototype;
    public int $num_args;
    public int $required_num_args;
    public ?zend_internal_arg_info $arg_info;
    public ?HashTable $attributes;
    public ?\FFI\CData $run_time_cache__ptr;
    public ?zend_string $doc_comment;
    public int $T;
    public ?zend_property_info $prop_info;
    public \FFI\CData|\Closure|null $handler;
    public ?zend_module_entry $module;
    public ?zend_frameless_function_info $frameless_function_infos;
    public \FFI\CData $reserved;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_lazy_objects_store'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_lazy_objects_store implements \ArrayAccess
{
    public HashTable $infos;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_lex_state'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_lex_state implements \ArrayAccess
{
    public int $yy_leng;
    public ?\FFI\CData $yy_start;
    public ?\FFI\CData $yy_text;
    public ?\FFI\CData $yy_cursor;
    public ?\FFI\CData $yy_marker;
    public ?\FFI\CData $yy_limit;
    public int $yy_state;
    public zend_stack $state_stack;
    public zend_ptr_stack $heredoc_label_stack;
    public zend_stack $nest_location_stack;
    public ?zend_file_handle $in;
    public int $lineno;
    public ?zend_string $filename;
    public ?\FFI\CData $script_org;
    public int $script_org_size;
    public ?\FFI\CData $script_filtered;
    public int $script_filtered_size;
    public \FFI\CData|\Closure|null $input_filter;
    public \FFI\CData|\Closure|null $output_filter;
    public ?\FFI\CData $script_encoding;
    public \FFI\CData|\Closure|null $on_event;
    public ?\FFI\CData $on_event_context;
    public ?zend_ast $ast;
    public ?zend_arena $ast_arena;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_live_range'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_live_range implements \ArrayAccess
{
    public int $var;
    public int $start;
    public int $end;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_llist'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_llist implements \ArrayAccess
{
    public ?zend_llist_element $head;
    public ?zend_llist_element $tail;
    public int $count;
    public int $size;
    public \FFI\CData|\Closure|null $dtor;
    public int $persistent;
    public ?zend_llist_element $traverse_ptr;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_llist_element'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_llist_element implements \ArrayAccess
{
    public ?zend_llist_element $next;
    public ?zend_llist_element $prev;
    public \FFI\CData $data;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_module_dep'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_module_dep implements \ArrayAccess
{
    public ?\FFI\CData $name;
    public ?\FFI\CData $rel;
    public ?\FFI\CData $version;
    public int $type;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_module_entry'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_module_entry implements \ArrayAccess
{
    public int $size;
    public int $zend_api;
    public int $zend_debug;
    public int $zts;
    public ?zend_ini_entry $ini_entry;
    public ?zend_module_dep $deps;
    public ?\FFI\CData $name;
    public ?_zend_function_entry $functions;
    public \FFI\CData|\Closure|null $module_startup_func;
    public \FFI\CData|\Closure|null $module_shutdown_func;
    public \FFI\CData|\Closure|null $request_startup_func;
    public \FFI\CData|\Closure|null $request_shutdown_func;
    public \FFI\CData|\Closure|null $info_func;
    public ?\FFI\CData $version;
    public int $globals_size;
    public \FFI\CData|\Closure|null $globals_ctor;
    public \FFI\CData|\Closure|null $globals_dtor;
    public \FFI\CData|\Closure|null $post_deactivate_func;
    public int $module_started;
    public int $type;
    public ?\FFI\CData $handle;
    public int $module_number;
    public ?\FFI\CData $build_id;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_object'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_object implements \ArrayAccess
{
    public zend_refcounted_h $gc;
    public int $handle;
    public int $extra_flags;
    public ?zend_class_entry $ce;
    public ?zend_object_handlers $handlers;
    public ?HashTable $properties;
    public \FFI\CData $properties_table;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_object_handlers'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_object_handlers implements \ArrayAccess
{
    public int $offset;
    public \FFI\CData|\Closure|null $free_obj;
    public \FFI\CData|\Closure|null $dtor_obj;
    public \FFI\CData|\Closure|null $clone_obj;
    public \FFI\CData|\Closure|null $read_property;
    public \FFI\CData|\Closure|null $write_property;
    public \FFI\CData|\Closure|null $read_dimension;
    public \FFI\CData|\Closure|null $write_dimension;
    public \FFI\CData|\Closure|null $get_property_ptr_ptr;
    public \FFI\CData|\Closure|null $has_property;
    public \FFI\CData|\Closure|null $unset_property;
    public \FFI\CData|\Closure|null $has_dimension;
    public \FFI\CData|\Closure|null $unset_dimension;
    public \FFI\CData|\Closure|null $get_properties;
    public \FFI\CData|\Closure|null $get_method;
    public \FFI\CData|\Closure|null $get_constructor;
    public \FFI\CData|\Closure|null $get_class_name;
    public \FFI\CData|\Closure|null $cast_object;
    public \FFI\CData|\Closure|null $count_elements;
    public \FFI\CData|\Closure|null $get_debug_info;
    public \FFI\CData|\Closure|null $get_closure;
    public \FFI\CData|\Closure|null $get_gc;
    public \FFI\CData|\Closure|null $do_operation;
    public \FFI\CData|\Closure|null $compare;
    public \FFI\CData|\Closure|null $get_properties_for;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_object_iterator'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_object_iterator implements \ArrayAccess
{
    public zend_object $std;
    public zval $data;
    public ?zend_object_iterator_funcs $funcs;
    public int $index;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_object_iterator_funcs'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_object_iterator_funcs implements \ArrayAccess
{
    public \FFI\CData|\Closure|null $dtor;
    public \FFI\CData|\Closure|null $valid;
    public \FFI\CData|\Closure|null $get_current_data;
    public \FFI\CData|\Closure|null $get_current_key;
    public \FFI\CData|\Closure|null $move_forward;
    public \FFI\CData|\Closure|null $rewind;
    public \FFI\CData|\Closure|null $invalidate_current;
    public \FFI\CData|\Closure|null $get_gc;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_objects_store'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_objects_store implements \ArrayAccess
{
    public ?\FFI\CData $object_buckets;
    public int $top;
    public int $size;
    public int $free_list_head;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_op'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_op implements \ArrayAccess
{
    public ?\FFI\CData $handler;
    public znode_op $op1;
    public znode_op $op2;
    public znode_op $result;
    public int $extended_value;
    public int $lineno;
    public int $opcode;
    public int $op1_type;
    public int $op2_type;
    public int $result_type;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_op_array'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_op_array implements \ArrayAccess
{
    public int $type;
    public \FFI\CData $arg_flags;
    public int $fn_flags;
    public ?zend_string $function_name;
    public ?zend_class_entry $scope;
    public ?zend_function $prototype;
    public int $num_args;
    public int $required_num_args;
    public ?zend_arg_info $arg_info;
    public ?HashTable $attributes;
    public ?\FFI\CData $run_time_cache__ptr;
    public ?zend_string $doc_comment;
    public int $T;
    public ?zend_property_info $prop_info;
    public int $cache_size;
    public int $last_var;
    public int $last;
    public ?zend_op $opcodes;
    public ?HashTable $static_variables_ptr__ptr;
    public ?HashTable $static_variables;
    public ?\FFI\CData $vars;
    public ?\FFI\CData $refcount;
    public int $last_live_range;
    public int $last_try_catch;
    public ?zend_live_range $live_range;
    public ?zend_try_catch_element $try_catch_array;
    public ?zend_string $filename;
    public int $line_start;
    public int $line_end;
    public int $last_literal;
    public int $num_dynamic_func_defs;
    public ?zval $literals;
    public ?\FFI\CData $dynamic_func_defs;
    public \FFI\CData $reserved;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_oparray_context'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_oparray_context implements \ArrayAccess
{
    public ?zend_oparray_context $prev;
    public ?zend_op_array $op_array;
    public int $opcodes_size;
    public int $vars_size;
    public int $literals_size;
    public int $fast_call_var;
    public int $try_catch_offset;
    public int $current_brk_cont;
    public int $last_brk_cont;
    public ?zend_brk_cont_element $brk_cont_array;
    public ?HashTable $labels;
    public ?zend_property_info $active_property_info;
    public int $active_property_hook_kind;
    public bool $in_jmp_frameless_branch;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_persistent_script'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_persistent_script implements \ArrayAccess
{
    public zend_script $script;
    public int $compiler_halt_offset;
    public int $ping_auto_globals_mask;
    public int $timestamp;
    public bool $corrupted;
    public bool $is_phar;
    public bool $empty;
    public int $num_warnings;
    public int $num_early_bindings;
    public ?\FFI\CData $warnings;
    public ?zend_early_binding $early_bindings;
    public ?\FFI\CData $mem;
    public int $size;
    public \FFI\CData $dynamic_members;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_property_info'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_property_info implements \ArrayAccess
{
    public int $offset;
    public int $flags;
    public ?zend_string $name;
    public ?zend_string $doc_comment;
    public ?HashTable $attributes;
    public ?zend_class_entry $ce;
    public zend_type $type;
    public ?zend_property_info $prototype;
    public ?\FFI\CData $hooks;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zend_property_info_source_list'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_property_info_source_list implements \ArrayAccess
{
    public ?zend_property_info $ptr;
    public int $list;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_ptr_stack'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_ptr_stack implements \ArrayAccess
{
    public int $top;
    public int $max;
    public ?\FFI\CData $elements;
    public ?\FFI\CData $top_element;
    public bool $persistent;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_refcounted'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_refcounted implements \ArrayAccess
{
    public zend_refcounted_h $gc;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_refcounted_h'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_refcounted_h implements \ArrayAccess
{
    public int $refcount;
    public zend_refcounted_h_u $u;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zend_refcounted_h.u'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_refcounted_h_u implements \ArrayAccess
{
    public int $type_info;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_reference'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_reference implements \ArrayAccess
{
    public zend_refcounted_h $gc;
    public zval $val;
    public zend_property_info_source_list $sources;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_resource'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_resource implements \ArrayAccess
{
    public zend_refcounted_h $gc;
    public int $handle;
    public int $type;
    public ?\FFI\CData $ptr;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_script'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_script implements \ArrayAccess
{
    public ?zend_string $filename;
    public zend_op_array $main_op_array;
    public HashTable $function_table;
    public HashTable $class_table;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_stack'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_stack implements \ArrayAccess
{
    public int $size;
    public int $top;
    public int $max;
    public ?\FFI\CData $elements;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_stream'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_stream implements \ArrayAccess
{
    public ?\FFI\CData $handle;
    public int $isatty;
    public \FFI\CData|\Closure|null $reader;
    public \FFI\CData|\Closure|null $fsizer;
    public \FFI\CData|\Closure|null $closer;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_string'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_string implements \ArrayAccess
{
    public zend_refcounted_h $gc;
    public int $h;
    public int $len;
    public \FFI\CData $val;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_strtod_state'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_strtod_state implements \ArrayAccess
{
    public \FFI\CData $freelist;
    public ?\FFI\CData $p5s;
    public ?\FFI\CData $result;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_trait_alias'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_trait_alias implements \ArrayAccess
{
    public zend_trait_method_reference $trait_method;
    public ?zend_string $alias;
    public int $modifiers;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_trait_method_reference'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_trait_method_reference implements \ArrayAccess
{
    public ?zend_string $method_name;
    public ?zend_string $class_name;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_trait_precedence'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_trait_precedence implements \ArrayAccess
{
    public zend_trait_method_reference $trait_method;
    public int $num_excludes;
    public \FFI\CData $exclude_class_names;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_try_catch_element'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_try_catch_element implements \ArrayAccess
{
    public int $try_op;
    public int $catch_op;
    public int $finally_op;
    public int $finally_end;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_type'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_type implements \ArrayAccess
{
    public ?\FFI\CData $ptr;
    public int $type_mask;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_type_list'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_type_list implements \ArrayAccess
{
    public int $num_types;
    public \FFI\CData $types;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zend_value'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_value implements \ArrayAccess
{
    public int $lval;
    public float $dval;
    public ?zend_refcounted $counted;
    public ?zend_string $str;
    public ?zend_array $arr;
    public ?zend_object $obj;
    public ?zend_resource $res;
    public ?zend_reference $ref;
    public ?zend_ast_ref $ast;
    public ?zval $zv;
    public ?\FFI\CData $ptr;
    public ?zend_class_entry $ce;
    public ?zend_function $func;
    public zend_value_ww $ww;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zend_value.ww'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zend_value_ww implements \ArrayAccess
{
    public int $w1;
    public int $w2;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'znode_op'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class znode_op implements \ArrayAccess
{
    public int $constant;
    public int $var;
    public int $num;
    public int $opline_num;
    public int $jmp_offset;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zval'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zval implements \ArrayAccess
{
    public zend_value $value;
    public zval_u1 $u1;
    public zval_u2 $u2;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zval.u1'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zval_u1 implements \ArrayAccess
{
    public int $type_info;
    public zval_u1_v $v;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C struct 'zval.u1.v'; the runtime value is always FFI\CData.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zval_u1_v implements \ArrayAccess
{
    public int $type;
    public int $type_flags;
    public zval_u1_v_u $u;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zval.u1.v.u'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zval_u1_v_u implements \ArrayAccess
{
    public int $extra;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}

/**
 * Analysis-only view of the engine C union 'zval.u2'; the runtime value is always FFI\CData.
 *
 * C union - only one member is meaningful at a time; the discriminant lives elsewhere.
 *
 * Indexable like the FFI handle it stands for: $view[$i] is the i-th element of
 * the pointed C array (the ArrayAccess shape is analysis-only, never executed).
 *
 * @internal
 */
final class zval_u2 implements \ArrayAccess
{
    public int $next;
    public int $cache_slot;
    public int $opline_num;
    public int $lineno;
    public int $num_args;
    public int $fe_pos;
    public int $fe_iter_idx;
    public int $guard;
    public int $constant_flags;
    public int $extra;

    private function __construct() {}

    public function offsetExists(mixed $offset): bool
    {
        return true;
    }

    public function offsetGet(mixed $offset): static
    {
        return $this;
    }

    public function offsetSet(mixed $offset, mixed $value): void {}

    public function offsetUnset(mixed $offset): void {}
}
