<?php

/**
 * Z-Engine framework
 *
 * @copyright Copyright 2019, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 */
declare(strict_types=1);

namespace ZEngine\System;

use FFI\CData;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use ZEngine\Core;
use ZEngine\Reflection\ReflectionValue;
use ZEngine\Type\OpLine;

class ExecutionDataTest extends TestCase
{
    public function testHasPrevious(): void
    {
        $hasPrevious = Core::$executor->getExecutionState()->hasPrevious();
        // This method is definitely called from PHPUnit, so it MUST contain previous entries
        $this->assertTrue($hasPrevious, 'This method is called from PHPUnit, it MUST contain previous entries');
    }

    public function testGetPrevious(): void
    {
        $executionData = Core::$executor->getExecutionState()->getPrevious();
        $this->assertInstanceOf(ExecutionData::class, $executionData);

        // We can compare our result with backtrace generated by debug_backtrace
        $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 2);
        $this->assertSame($trace[1]['function'], $executionData->getFunction()->getName());
    }

    public function testGetSymbolTableIsNullWithoutMaterializedTable(): void
    {
        // Ordinary frames keep their locals in CV slots and never materialize a
        // symbol table: the field is stale garbage then (the historical segfault of
        // this method), so the accessor reports the absence as null instead
        $this->assertNull(Core::$executor->getExecutionState()->getSymbolTable());
    }

    public function testGetSymbolTableReadsMaterializedTable(): void
    {
        $localValue = 'observable-through-symbol-table';
        get_defined_vars(); // Triggers zend_rebuild_symbol_table() for this frame

        $symbolTable = Core::$executor->getExecutionState()->getSymbolTable();
        $this->assertNotNull($symbolTable);

        // Rebuilt tables alias the live CV slots through IS_INDIRECT entries
        $entry = $symbolTable->find('localValue');
        $this->assertNotNull($entry);
        $this->assertSame(ReflectionValue::IS_INDIRECT, $entry->getType());
        $entry->getIndirectValue()->getNativeValue($resolvedValue);
        $this->assertSame($localValue, $resolvedValue);
    }

    /**
     * This test is tricky one to understand: PHP engine allocates a stack frame, where each variable is stored in
     * the stack frame. Thus, $a variable will be stored in first slot in the stack frame and we can access it to check
     */
    public function testGetCallVariableByNumber(): void
    {
        // Do not use constants here to prevent opcode optimization and inlining
        $expected = microtime(true);

        // $expected will be the first temporary variable in the stack, so index will be 0
        $value = Core::$executor->getExecutionState()->getCallVariableByNumber(0);
        $this->assertInstanceOf(CData::class, $value);

        // Let's check if this value equals to our original $expected
        ReflectionValue::fromValueEntry($value)->getNativeValue($return);
        $this->assertNotNull($return);
        $this->assertSame($expected, $return);
    }

    public function testGetLocalVariables(): void
    {
        // Do not use constants here to prevent opcode optimization and inlining
        $expected = microtime(true);
        $another  = 'local-' . __FUNCTION__;

        $locals = Core::$executor->getExecutionState()->getLocalVariables();

        // $locals itself (and everything below) was still IS_UNDEF at observation
        // time, so only the two assigned variables are visible
        $this->assertSame(['expected', 'another'], array_keys($locals));
        $locals['expected']->getNativeValue($expectedValue);
        $locals['another']->getNativeValue($anotherValue);
        $this->assertSame($expected, $expectedValue);
        $this->assertSame($another, $anotherValue);
    }

    public function testGetLocalVariableByName(): void
    {
        $marker = 'observable-frame-value';

        $state = Core::$executor->getExecutionState();
        $state->getLocalVariable('marker')->getNativeValue($markerValue);
        $this->assertSame($marker, $markerValue);
    }

    public function testGetLocalVariableObservesUndefSlot(): void
    {
        $probe = random_int(0, 0);
        if ($probe > 0) {
            $conditional = 'assigned only for a positive probe';
        }

        $state = Core::$executor->getExecutionState();
        if (!$state->hasLocalVariable('conditional')) {
            // The opcache optimizer proved the branch dead (random_int range inference)
            // and dropped the never-assigned CV from the frame entirely: the documented
            // contract is then a throw from the by-name reader, probed via
            // hasLocalVariable() first
            $this->expectException(\OutOfBoundsException::class);
        }

        // The CV slot exists on the frame (compile-time allocation) but was never
        // assigned on this code path: unlike getLocalVariables() the by-name reader
        // exposes it so callers can distinguish "declared but unset"
        $undefined = $state->getLocalVariable('conditional');
        $this->assertSame(ReflectionValue::IS_UNDEF, $undefined->getType());
    }

    public function testGetLocalVariableRejectsUnknownName(): void
    {
        $this->expectException(\OutOfBoundsException::class);
        $this->expectExceptionMessage('no compiled variable $missing');
        Core::$executor->getExecutionState()->getLocalVariable('missing');
    }

    public function testGetLocalVariablesOfParentFrame(): void
    {
        $marker = 'parent-frame-marker';

        [$markerHasSlot, $observed] = (function (): array {
            // The closure's own frame is the current state; its caller is this test
            $parentFrame  = Core::$executor->getExecutionState()->getPrevious();
            $parentLocals = $parentFrame->getLocalVariables();

            $values = [];
            foreach ($parentLocals as $name => $valueEntry) {
                $valueEntry->getNativeValue($value);
                $values[$name] = $value;
                unset($value);
            }

            return [$parentFrame->hasLocalVariable('marker'), $values];
        })();

        if ($markerHasSlot) {
            $this->assertSame(['marker' => $marker], $observed);
        } else {
            // The opcache optimizer propagated the literal into its use site and dropped
            // the dead store, so the parent frame has no marker CV at all - and the frame
            // reader reports that consistently instead of inventing a value
            $this->assertSame([], $observed);
        }
    }

    public function testHasLocalVariableAndNamesReflectTheFrame(): void
    {
        // A runtime-computed value: the optimizer cannot fold it into its use site, so
        // the CV slot survives any optimization level and the probes stay deterministic
        $marker = random_int(1, PHP_INT_MAX);

        $state = Core::$executor->getExecutionState();
        $this->assertTrue($state->hasLocalVariable('marker'));
        $this->assertFalse($state->hasLocalVariable('missing'));
        $this->assertContains('marker', $state->getLocalVariableNames());

        $state->getLocalVariable('marker')->getNativeValue($observedMarker);
        $this->assertSame($marker, $observedMarker);
    }

    #[DataProvider('argumentProvider')]
    public function testGetArguments(mixed $arg1 = null, mixed $arg2 = null, mixed $arg3 = null): void
    {
        $engineArguments   = Core::$executor->getExecutionState()->getArguments();
        $receivedArguments = [];
        foreach ($engineArguments as $reflectionValue) {
            // We can collect original PHP values from the Core one-by-one
            $reflectionValue->getNativeValue($value);
            $receivedArguments[] = $value;
            unset($value);
        }
        $this->assertEquals(func_get_args(), $receivedArguments);
    }

    #[DataProvider('argumentProvider')]
    public function testGetNumberOfArguments(mixed ...$args): void
    {
        $engineArguments = Core::$executor->getExecutionState()->getNumberOfArguments();
        $expectedNumber  = func_num_args();
        $this->assertSame($expectedNumber, $engineArguments);
    }

    #[DataProvider('argumentProvider')]
    public function testGetArgument(mixed $firstPhpArgument, mixed ...$rest): void
    {
        // Be aware, that getArgument() can return only declared arguments, not extra one!
        $firstArgument = Core::$executor->getExecutionState()->getArgument(0);

        $firstArgument->getNativeValue($firstEngineValue);
        $this->assertInstanceOf(ReflectionValue::class, $firstArgument);
        $this->assertSame($firstPhpArgument, $firstEngineValue);
    }

    /**
     * @return list<list<mixed>>
     */
    public static function argumentProvider(): array
    {
        return [
            [1],
            ['a', false],
            [null, new \stdClass(), 42.0],
        ];
    }

    public function testGetOpline(): void
    {
        $opline = Core::$executor->getExecutionState()->getOpline();
        $this->assertSame(__LINE__ - 1, $opline->getLine());
        // we can't do more at the current stage, because code is already executed and we are not in opcode handler
        $this->assertInstanceOf(OpLine::class, $opline);
    }

    public function testGetThis(): void
    {
        $thisValue = Core::$executor->getExecutionState()->getThis();
        $this->assertNotNull($thisValue);
        $thisValue->getNativeValue($instance);
        $this->assertSame($this, $instance);

        // Just for fun: we can do crazy things like changing $this in current stack frame
        $self = $this; // Save current $this to call method on it later
        $thisValue->setNativeValue(new \stdClass());
        $self->assertInstanceOf(\stdClass::class, $this);
    }

    public function testHasThisAndGetThisForInstanceMethodFrame(): void
    {
        $state = Core::$executor->getExecutionState();

        // A method frame carries a bound object: its This zval reads as
        // IS_OBJECT_EX plus call-info bits, never a bare IS_OBJECT
        $this->assertTrue($state->hasThis());

        $thisObject = $state->getThis();
        $this->assertNotNull($thisObject);
        $thisObject->getNativeValue($instance);
        $this->assertSame($this, $instance);
    }

    public function testHasThisAndGetThisForStaticMethodFrame(): void
    {
        [$hasThis, $thisObject] = self::observeFrameObjectScopeFromStaticMethod();

        $this->assertFalse($hasThis);
        $this->assertNull($thisObject);
    }

    public function testHasThisAndGetThisForPlainFunctionFrame(): void
    {
        // A static closure frame is a plain function frame: no bound object scope
        [$hasThis, $thisObject] = (static function (): array {
            $state = Core::$executor->getExecutionState();

            return [$state->hasThis(), $state->getThis()];
        })();

        $this->assertFalse($hasThis);
        $this->assertNull($thisObject);
    }

    /**
     * @return array{0: bool, 1: ?ReflectionValue}
     */
    private static function observeFrameObjectScopeFromStaticMethod(): array
    {
        $state = Core::$executor->getExecutionState();

        return [$state->hasThis(), $state->getThis()];
    }

    public function testGetFunction(): void
    {
        $reflectionFunction = Core::$executor->getExecutionState()->getFunction();
        $this->assertSame(__FUNCTION__, $reflectionFunction->getName());
    }

    public function testGetCallVariable(): void
    {
        $this->markTestSkipped('Very engine-specific method');
    }

    public function testGetReturnValue(): void
    {
        $this->markTestSkipped('It is impossible to check this method, because return value will be overridden by PHP');
    }
}
